<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/1000-razones/1000-razones-home.jpg')"></div>
                   </div>
               </div>
         
            
            <div class="carousel-caption">
                <h2 class="text-uppercase txt-220"><?php echo $titulo?></h2>
                <h3 style="font-weight: 300">Y sólo una para convencerte</h3>
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12 text-center">
                <h3>Tenemos una razón para que desconectes:</h3>
                <h1 class="color-accion">1.000 habitaciones en OCA a solo 30€</h1>
               
                 
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-sm-8 col-sm-push-2"> <p><br>
                  Oca Hotels quiere arrancar la temporada con este premio a sus huéspedes.  </p>
                <h3 style="line-height: inherit">Haz tu <u>reserva</u> entre los días <u>14 y 22 de octubre</u> de 2017 y disfruta de tu estancia a 30€ la noche durante <u>todo el mes de noviembre</u>.</h3>
                <p>La promoción tiene validez en los hoteles Oca con presencia en España</p></div>
            <hr>
            <img src="http://ocahotels.com/images/1000-razones/1000-razones.gif" class="img-responsive" style="margin: 0 auto;">
            <hr>
              <div class="col-xs-12 col-xs-push-0 col-sm-8 col-sm-push-2">
                <p>Oca Hotels, que cuenta con más de 20 hoteles repartidos en distintos puntos de Galicia, Asturias, Salamanca y Brasil, se caracteriza por ofrecer una alojamientos adaptados a un público muy amplio. Entre sus características y actividades, se encuentran lugares especializados en la práctica de deportes de montaña para adultos y niños (bikes, campamentos, tirolina...), hoteles con excelentes campos golf o balnearios de aguas mineromedicinales, ideados para relajarse y disfrutar del mejor turismo de salud. </p>
                <p class="small">Precio por habitación doble, IVA incluido.<br>
                    Régimen: Sólo alojamiento.<br>
                    Sujeto a disponibilidad de la oferta en cada hotel.<br>
No válido para Grand Oca Maragogi.</p>
               </div>
    </div>
    
</section>
<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



