<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/augas-santas/inicio/00001-inicio.jpg')"></div>
                   </div>
               </div>
         

    <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/palacio-llorea/spa/modelos%20spa%20(2).JPG')"></div>
                   </div>
               </div>
            
            <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/allariz/spa/9f24a17318e081e493cea64c86e5c0f0b86d6f55.jpg')"></div>
                   </div>
               </div>
            
              <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/rio-pambre/balneario/001-balneario.jpg')"></div>
                   </div>
               </div>


            
            <div class="carousel-caption">
                <h1 class="text-uppercase ">Hoteles con SPA, balneario y aguas termales</h1>
                <h2 style="font-size:1.3em !important; font-weight: 300;">Disfrute de los SPA y balnearios de los hoteles OCA en Gijón, Lugo y Ourense</h2>
              
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="breadcrumb pd-l-0"><a href="/">OCA HOTELS</a> > <a href="/experiencias">EXPERIENCIAS</a> > SPA Y SALUD</div>
           <div class="ol-xs-12 col-xs-push-0  col-md-12 col-lg-5">
              
               <h3 style="line-height: inherit">Sumérjase en un profundo estado de relajación con los servicios wellness de Oca Hotels.</h3>
               
               <h4 style="line-height: inherit;">Entre nuestros hoteles encontrará una gran oferta de spa y balnearios, entre los que se ofrecen algunos de los mejores tratamientos wellness de España.</h4><hr>    
               <h5 class="text-center">
                   <i class="icon-estrella-2 txt-200"></i><br><br>Finalistas en los premios Wellness & Spa Experience:<br>Mejor Balneario y Mejor Técnica Termal o Wellness</h5><hr>
           
                
               <p>Elija entre sumergirse en el poder sanador de las aguas minerales de nuestros balnearios o disfrutar de infinidad de tratamientos spa que le sumirán en un profundo estado de relajación, ambos tratamientos perfectos para dejar atrás los problemas y la rutina del día a día.</p>
               <p>Pregunte por nuestros menús para la ocasión o configure un menú a su medida, incluyendo los menús especiales para personas con algún tipo de alergia o intolerancia alimentaria.</p>
               <p>Nuestros balnearios y spas están equipados con lo último en equipamiento:</p>
               <ul><li>Baños de burbuja e hidromasaje<li>Chorro termal</li> <li>Piscina activa</li><li>Cuellos de cisne </li><li>Camas de agua</li><li>Cabina de hielo</li><li>Sauna</li><li>Baño turco</li><li>Chorros a presión</li><li>Cascadas…</li>
    </ul>
               <br><p>Nuestros masajes, estiramientos y diversos tratamientos (faciales, envolvimientos de lino y algas…) cierran la mejor oferta en descanso que encontrará usted en la zona.</p>
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-lg-6 col-lg-push-1"> 
  
                  
                
                
              
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 210px;background-image: url('/images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 210px;height: 210px;">

                        <a href="/hoteles/espana/asturias/gijon/oca-palacio-llorea/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Palacio de la Llorea</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Gijón</h5>
                             <a href="/destinos/asturias/"><h5 class="color-blanco font-light txt-100 mg-t-0">Asturias</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
                
               
                
                
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 210px;background-image: url('/images/hoteles/augas-santas/augas-santas-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 210px;height: 210px;">

                        <a href="/hoteles/espana/lugo/panton/oca-augas-santas/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Augas Santas</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Pantón</h5>
                              <a href="/destinos/lugo/"><h5 class="color-blanco font-light txt-100 mg-t-0">Lugo</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
             
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 210px;background-image: url('/images/hoteles/rio-pambre/rio-pambre-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 210px;height: 210px;">
                        <a href="/hoteles/espana/lugo/palas-de-reis/oca-rio-pambre/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Río Pambre</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Palas de Reis</h5>
                         <a href="/destinos/lugo/"><h5 class="color-blanco font-light txt-100 mg-t-0">Lugo</h5></a>
                                           </div>
                 </div>
                            </div>
                
                  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 210px;background-image: url('/images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 210px;height: 210px;">

                        <a href="/hoteles/espana/ourense/allariz/oca-allariz/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 16px !important; text-shadow: 2px 1px 1px black;">Vila de Allariz</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Allariz</h5>
                         <a href="/destinos/ourense/"><h5 class="color-blanco font-light txt-100 mg-t-0">Ourense</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
            
        
                       

                
              
                
                
                     
                     
                       
                        
    
             

               </div>
          
           
    </div>
    </div>
</section>



<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



