<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles-para-eventos/hoteles-para-eventos-home.jpg')"></div>
                   </div>
               </div>
         
            
            <div class="carousel-caption">
                <h2 class="text-uppercase txt-220"><?php echo $titulo?></h2>
                <h3 style="font-weight: 300">Celebre su evento con garantías de éxito en Oca Hotels</h3>
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
           <div class="ol-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2 text-center">
              
               <h2 class="color-accion" style="line-height: inherit">Gracias nuestras completas instalaciones su evento será perfecto.</h2>
               
                 
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2"> 
                <h4 style="line-height: inherit;">Ideales para cualquier tipo de ventos relacionados con la empresa, tales como jornadas de convivencia, actividades de coaching, seminarios, reuniones de grupo, presentación de productos y cualquier tipo de convención o congreso en general.</h4>
                
                <p> Gozamos de amplias salas, elegantes y versátiles, adaptándose a cualquier tipo de evento con todo tipo de montajes. Además, un equipo de profesionales con gran experiencia en la organización y gestión de eventos le asesorará para preparar su evento ajustándose a su presupuesto.  </p>
                <p>
                 Amplia oferta gastronómica a cargo de nuestros chefs, gran capacidad, accesibilidad, facilidad de aparcamiento y un gran equipo humano, cierran una oferta perfecta que garantiza que su evento será todo un éxito.
                </p>
            <br>
                    <a href="https://podio.com/webforms/19688648/1334904?fields[en-que-esta-interesad]=5" target="_blank" class="pdflink"><h4>SOLICITAR INFORMACIÓN</h4></a>
               </div>
          
           
    </div>
    </div>
</section>



<div id="contenedor-boxes" style="display: block;"><section class="bck-color-blanco">
    <div class="container-fluid ">
        
        <div class="row boxes-destinos">
        
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/aldeaduero/aldeaduero-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Aldeaduero</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Salamanca, Castilla y León</p>

                        <a href="/hoteles/espana/castilla-y-leon/salamanca/oca-hotel-oca-aldeaduero/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/augas-santas/augas-santas-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Augas Santas</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Pantón, Lugo</p>

                        <a href="/hoteles/espana/lugo/panton/oca-augas-santas/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Palacio de la Llorea</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Gijón, Asturias</p>

                        <a href="/hoteles/espana/asturias/gijon/oca-palacio-llorea/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/puerta-del-camino/puerta-del-camino-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Puerta del camino</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-puerta-del-camino/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/santo-domingo-plaza/santo-domingo-plaza-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Santo Domingo Plaza</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Oviedo, Asturias</p>

                        <a href="/hoteles/espana/asturias/oviedo/oca-santo-domingo-plaza/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Vila de Allariz</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Allariz, Ourense</p>

                        <a href="/hoteles/espana/ourense/allariz/oca-allariz/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        
        </div>
        
    </div>
</section>
</div>
<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



