<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/hotel-oca-aldeaduero/entorno/0001-entorno-aldeaduero.jpg')"></div>
                   </div>
               </div>
         


            
            <div class="carousel-caption">
                <h1 class="text-uppercase ">Hoteles en Castilla y León</h1>
                <h2 style="font-size:1.3em !important; font-weight: 300;">Encuentre habitaciones de hotel, apartamentos y chalets rurales en Salananca.</h2>
              
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="breadcrumb pd-l-0"><a href="/">OCA HOTELS</a> > <a href="/destinos">DESTINOS</a> > CASTILLA Y LEÓN</div>
           <div class="ol-xs-12 col-xs-push-0  col-md-12 col-lg-6">
              
               <h3 style="line-height: inherit">Descubra la belleza del Parque Natural do Douro Internacional en los hoteles, apartamentos y alojamientos rurales de OCA Hotels.</h3>
               
                 <h4 style="line-height: inherit;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h4>
                
                <p> 
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <br>
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-lg-5 col-lg-push-1"> 
  
        
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 150px;background-image: url('/images/hoteles/aldeaduero/aldeaduero-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 150px;height: 150px;">

                        <a href="/hoteles/espana/castilla-y-leon/salamanca/oca-hotel-oca-aldeaduero/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Aldeaduero</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Salamanca</h5>
                       
                    </div>
 
                </div>
                
            </div>
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 150px;background-image: url('/images/hoteles/duerming-aldeaduero/duerming-aldeaduero-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 150px;height: 150px;">
                        <a href="/hoteles/espana/castilla-y-leon/salamanca/oca-hotel-duerming-aldeaduero/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Duerming Aldeaduero</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Salamanca</h5>
                                           </div>
                 </div>
                            </div>
                
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 150px;background-image: url('/images/hoteles/chalets-aldeaduero/chalets-aldeaduero-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 150px;height: 150px;">
                        <a href="/hoteles/espana/castilla-y-leon/salamanca/oca-chalets-rurales-aldeaduero/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Chalets Aldeaduero</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                    
                                                                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Salamanca</h5>
                                           </div>
                 </div>
                            </div>
                
                     

                
                
                     
                     
                       
                        
    
             

               </div>
          
           
    </div>
    </div>
</section>



<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



