<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs1-2">
                <h3><?php echo _("RSC")?></h3>
                
                 <h4>
                    Corporate Social Responsibility</h4>
                <p>Oca Hotels keeps a strong commitment to the environment, local culture and conservation of the historic elements of the cities in which our hotels can be found.</p>
                <p>
These values make Oca Hotels a responsible and sustainable choice for our stakeholders group, with whom we are in constant dialogue to extend our frontiers regarding the conservation of our environment and culture. 
</p>

               
                
                
                
            </div>
        </div>
    </div>
    
</section>