<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs1-2">
                <h3><?php echo _("RSC")?></h3>
                
                 <h4>
                     Responsabilidad Social Corporativa</h4>
                <p>Oca Hotels mantiene un serio compromiso con el medioambiente, la cultura local y la conservación de los elementos históricos de las ciudades en las que se encuentran nuestros hoteles. </p>
                <p>
Estos valores hacen de Oca Hotels una elección responsable y sostenible por parte de nuestros Grupos de Interés, con los que mantenemos un diálogo constante para ampliar nuestras fronteras en cuanto a conservación de nuestro entorno y cultura.
</p>

               
                
                
                
            </div>
        </div>
    </div>
    
</section>