<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Empleo")?></h3>
                
                <p>
                    En Oca Hotels trabajamos constantemente por alcanzar la <strong>excelencia en el servicio a nuestros clientes</strong> y sabemos de sobra que esa meta solo se alcanza si se cuenta con un equipo humano con experiencia y correctamente motivado. Es por ello que en Oca Hotels buscamos constantemente personal con talento, ilusión y afán de superación personal, que quiera sumarse a nuestro proyecto y cumplir sus sueños sumándose a nuestro equipo. Si eres esa persona, no dudes en rellenar el cuestionario que encontrarás a continuación, con el que entrarás en el <strong>proceso de selección de personal de Grupo Oca</strong>.
                </p>
                
                <p>
                    Rellene nuestro formulario de recepción de CVs.<br>
                    Le recordamos que al enviarnos su CV acepta nuestra <a data-toggle="modal" data-target="#cvModal" style="font-weight: bold">política de LOPD</a>.
                </p>
                
                <div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
               <!-- BEGIN Podio web form -->
<script src="https://podio.com/webforms/19128019/1287562.js"></script>
<script type="text/javascript">
  _podioWebForm.render("1287562")
</script>
<noscript>
  <a href="https://podio.com/webforms/19128019/1287562" target="_blank">Por favor, rellena el formulario</a>
</noscript>

<!-- END Podio web form -->

            </div>
                
        </div>
    </div>
    </div>
    
</section>


<!-- Modal -->
<div class="modal fade" id="cvModal" tabindex="-1" role="dialog" aria-labelledby="cvModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Contestación Currículums</h4>
      </div>
      <div class="modal-body">
         
          <p  align="justify"> A los efectos establecidos en el Reglamento General (UE) 2016/679 de Protección de Datos, INVERSIONES HOSTELERAS DE GALICIA, S.L., con CIF número B 36348217 y domicilio social en C/ Miguel Ferro Caaveiro, s/n, 15.703, Santiago de Compostela (A Coruña) le informa que incorpora sus datos personales, junto a su fotografía, si usted nos la proporciona, incluyendo aquellos datos considerados sensibles que usted nos proporciona, a un Tratamiento de titularidad privada para los siguientes fines: establecer y mantener una relación contractual con usted, valorar su adecuación a un puesto de trabajo o tarea, así como para notificarle de oportunidades de empleo y  para todo fin permitido por la Ley. </p>
<p align="justify"> <br/>
</p>
<p  align="justify"> En caso de producirse alguna modificación en sus datos, le rogamos nos lo comunique debidamente. </p>
<p align="justify"> <br/>
</p>
<p  align="justify"><a name="_GoBack"></a> Del mismo modo Inversiones Hosteleras de Galicia S.L le informa que, para los fines arriba indicados, los datos de carácter personal que nos proporciona podrán  ser cedidos  a empresas del grupo OCA HOTELS con la finalidad anteriormente indicada.</p>
<p align="justify"> <br/>
</p>
<p  align="justify"> Si no estuviera conforme con alguno de los puntos señalados anteriormente, le rogamos nos lo comunique por escrito en el plazo de 10 días desde la recepción de la presente comunicación. </p>
<p align="justify"> <br/>
</p>
<p  align="justify"> Asimismo, le comunicamos que su currículum será almacenado por un período máximo de 2 años, pudiendo destruirse en cualquier momento si no encaja con el perfil de la empresa. </p>
<p align="justify"> <br/>
</p>
<p  align="justify"> Puede ejercitar los derechos de acceso, rectificación, supresión, limitación, oposición y portabilidad en cualquier momento, así como revocar el consentimiento prestado, en cada comunicado que se le haga llegar, mediante escrito, acompañado de copia de documento oficial que le identifique dirigido a la dirección arriba reseñada o en la dirección <a href="mailto:lopd@ocahotels.es">lopd@ocahotels.es</a>.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">X</button>
    
      </div>
    </div>
  </div>
</div>