<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Empleo")?></h3>
                
                <p>
                  At Oca Hotels we constantly work towards the achievement of excellence in the service to our customers, knowing that this goal will be achieved only if we count on an experienced and correctly motivated human team. Because of that, at Oca Hotels we are constantly looking for talented, enthusiastic staff who have constant endeavour to improve, who desire to become part of our project and make their dreams come true by becoming one of us. If you are that kind of person, do not hesitate to fill the application that you will find below; with it, you will enter the staff selection process by the Oca Group.
                </p>
                
                <p>
                 Please, fill in the reception of our CV application form.<br>
                  We remind you that by sending us your CV you accept our <a data-toggle="modal" data-target="#cvModal" style="font-weight: bold">Organic Law of Data Protection</a>.
                </p>
                
                <div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
               <!-- BEGIN Podio web form -->
<script src="https://podio.com/webforms/19128019/1287562.js"></script>
<script type="text/javascript">
  _podioWebForm.render("1287562")
</script>
<noscript>
  <a href="https://podio.com/webforms/19128019/1287562" target="_blank">Por favor, rellena el formulario</a>
</noscript>

<!-- END Podio web form -->

            </div>
                
        </div>
    </div>
    </div>
    
</section>


<!-- Modal -->
<div class="modal fade" id="cvModal" tabindex="-1" role="dialog" aria-labelledby="cvModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">CV submission</h4>
      </div>
      <div class="modal-body">
         
         <p>For the purposes established in the Organic Law 15/1999, of December 13, for the Protection of Personal Data, <b> INVERSIONES HOSTELERAS DE GALICIA, SL </ b> with CIF B36348217 and address at C / Miguel Ferro Caaveiro, s / n, 15.703, Santiago de Compostela (A Coruña), informs you that it incorporates your personal data, together with your photograph, if you provide it to us, including those data considered sensitive that you provide us, to a file of private ownership registered in the Spanish Agency for Data Protection for the following purposes: establish and maintain a contractual relationship with you, assess your adequacy to a job or task, as well as to notify you of employment opportunities and for all purposes permitted by law. </ p>
          <p>In case of any change in your data, please inform us accordingly. </ p>
          <p>Inversiones Hosteleras de Galicia SL informs you that, for the purposes indicated above, the personal data you provide may be transferred to companies of the <b> OCA HOTELS </ b> group for the above-mentioned purpose </ p >
          <p>If you are not satisfied with any of the points indicated above, please inform us in writing within 10 days. </ p>
          <p>Likewise, we inform you that your CV will be stored for a maximum period of 2 years, and may be destroyed at any time if it does not fit the profile of the company. </ p>
          <p>You can exercise the rights of access, rectification, cancellation and opposition at any time, as well as revoke the consent given, in each communication sent to you, in writing, accompanied by a copy of an official document that identifies you addressed to the above address or in <a href="mailto:lopd@ocahotels.es"> lopd@ocahotels.es </a>. </ p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">X</button>
    
      </div>
    </div>
  </div>
</div>