<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12 text-left">
                <h3><?php echo _("Reservas telefónicas")?></h3>
                
                 <p>
                     <?php echo _("Si desea hacer su reserva por teléfono, llame directamente a nuestro servicio de reservas en cada hotel:")?></p>
 
                 <ul>
                     <li>Grand Oca Maragogi Resort:<br class="visible-xs">(+55) 823 296 3200</li>
                     <li>Hotel Oca Aldeaduero:<br class="visible-xs"> (+34) 923 51 31 75</li>
                     <li>Oca Augas Santas:<br class="visible-xs"> (+34) 982 29 28 00</li>
                     <li>Oca Palacio de la Llorea:<br class="visible-xs"> (+34) 985 13 18 12</li>
                     <li>Oca Puerta del Camino:<br class="visible-xs"> (+34) 981 56 94 00</li>
                     <li>Oca Santo Domingo Plaza:<br class="visible-xs"> (+34) 985 20 78 80</li>
                     <li>Oca Vila de Allariz:<br class="visible-xs"> (+34) 988 55 40 40</li>
                     <li>Hotel Duerming Aldeaduero:<br class="visible-xs"> (+34)  923 51 31 75</li>
                     <li>Hotel Duerming Justo:<br class="visible-xs"> (+34) 986 69 07 50</li>
                     <li>Oca Insua Costa da Morte:<br class="visible-xs"> (+34) 981 74 75 75</li>
                     <li>Oca Ipanema Hotel:<br class="visible-xs"> (+34) 986 47 13 44</li>
                     <li>Oca Río Pambre:<br class="visible-xs"> (+34) 982 15 32 32</li>
                     <li>Oca Vermar Hotel:<br class="visible-xs"> (+34) 986 72 70 22</li>
                     <li>Hotel Duerming San Vicente:<br class="visible-xs"> (+34) 687 16 30 02</li>
                     <li>Hotel Duerming Villa de Sarria:<br class="visible-xs"> (+34) 982 53 38 73</li>
                     <li>Apartamentos Duerming Cruceiro do Galo:<br class="visible-xs"> (+34) 687 16 30 02</li>
                     <li>Duerming Sete Artes Hotel Boutique:<br class="visible-xs"> (+34) 881 16 24 87</li>
                     <li>Estación de Montaña Oca Nova Manzaneda:<br class="visible-xs"> (+34) 988 30 90 90</li>
                     <li>Apartamentos Duerming Bolera-Pico:<br class="visible-xs"> (+34) 981 10 10 74</li>
                     <li>Apartamentos Duerming Portonovo Pico:<br class="visible-xs"> (+34) 981 10 10 74</li>
                     <li>Apartamentos Duerming Sea View Vivero:<br class="visible-xs"> (+34) 687 16 30 02</li>
                     <li>Apartamentos Oca Casas Reales:<br class="visible-xs"> (+34) 687 16 30 02</li>
                     <li>V.V. Duerming Sanxenxo Residences:<br class="visible-xs"> (+34) 986 72 06 07</li>
                     <li>Oca Aldeaduero:<br class="visible-xs"> (+34) 923 51 31 75</li>
                     <li>Oca Rua Travesa:<br class="visible-xs"> (+34) 687 16 30 02</li>
                       <li>Oca Villa de Avilés:<br class="visible-xs"> (+34) 985 526 116</li>
                 </ul>
                 
               






















               
                
                
                
            </div>
        </div>
    </div>
    
</section>