<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3>Duerming</h3>
                
                <h4>Duerming, brand associated to Oca Hotels Group.</h4>
                
                <p>
                   Hotels and holiday apartments Duerming is a brand belonging to Oca Hotels chain. Under the Duerming brand, we develop the business philosophy of our group under a new identity creating, thus, a series of functional hotels and establishing as our pillars the usefulness of its facilities and attentive attitude towards our customers. </p>
                <p>
 
Duerming and Oca Hotels share the same commitment and corporate identity that leads them to offer a high-quality, innovative and efficient service. We seek excellency of management, always bearing in mind our priority: to satisfy and to provide personal attention to all the needs of each and every one of our clients. 

                </p>
                
                
            </div>
        </div>
    </div>
    



<div class="row boxes-destinos">
        
    
    
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/duerming-aldeaduero/duerming-aldeaduero-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Duerming Aldeaduero</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Salamanca, Castilla y León</p>

                        <a href="/en/hoteles/espana/castilla-y-leon/salamanca/oca-hotel-duerming-aldeaduero/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/justo/justo-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Justo</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sanxenxo, Pontevedra</p>

                        <a href="/en/hoteles/espana/pontevedra/sanxenxo/oca-justo/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                     
                    
                    
                     
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/san-vicente/san-vicente-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>San Vicente</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">O Grove, Pontevedra</p>

                        <a href="/en/hoteles/espana/pontevedra/o-grove/oca-san-vicente/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/vila-de-sarria/vila-de-sarria-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Vila de Sarria</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sarria, Lugo</p>

                        <a href="/en/hoteles/espana/lugo/sarria/oca-villa-de-sarria/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/cruceiro-do-galo/cruceiro-do-galo-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Cruceiro do Galo</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/en/hoteles/espana/a-coruna/santiago-de-compostela/oca-apartamentos-cruceiro-do-galo/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/sete-artes/sete-artes-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Sete Artes</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/en/hoteles/espana/a-coruna/santiago-de-compostela/oca-sete-artes/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                      
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/bolera-pico/bolera-pico-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Bolera Pico</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sanxenxo, Pontevedra</p>

                        <a href="/en/hoteles/espana/pontevedra/sanxenxo/oca-portonovo-pico2/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/portonovo-pico/portonovo-pico-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Portonovo Pico</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sanxenxo, Pontevedra</p>

                        <a href="/en/hoteles/espana/pontevedra/sanxenxo/oca-portonovo-pico/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/sea-view-viveiro/sea-view-viveiro-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Sea View Viveiro</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Viveiro, Lugo</p>

                        <a href="/en/hoteles/espana/lugo/viveiro/oca-apartamentos-seaview-viveiro/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/casa-reales/casa-reales-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Casa Reales</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/en/hoteles/espana/a-coruna/santiago-de-compostela/oca-casas-reales/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/sanxenxo/sanxenxo-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Sanxenxo</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sanxenxo, Pontevedra</p>

                        <a href="/en/hoteles/espana/pontevedra/sanxenxo/oca-sanxenxo-residence/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/chalets-aldeaduero/chalets-aldeaduero-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Chalets Aldeaduero</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                    </div>
                        <p class="color-blanco font-light txt-130">Salamanca, Castilla y León</p>

                        <a href="/en/hoteles/espana/castilla-y-leon/salamanca/oca-chalets-rurales-aldeaduero/" class="btn btn-primary-box mg-t-50" style="top:0;">DISCOVER IT</a>
                      
                    </div>
 
                </div>
                
            </div>
                        
        </div>
    
    </section>