<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Duerming")?></h3>
                
                <h4>Duerming, marca asociada al Grupo Oca Hotels</h4>
                
                <p>
                    Duerming hoteles y apartamentos es una marca perteneciente a la cadena Oca Hotels. Bajo la marca Duerming, desarrollamos la filosofía comercial del grupo bajo una nueva identidad,  creando una serie de hoteles funcionales, que hace de la utilidad de sus instalaciones y la atención en el trato al cliente sus pilares principales.</p>
                <p>
 
Duerming y Oca Hotels comparten un compromiso y una identidad corporativa común que les lleva a ofrecer un servicio de calidad, innovador y eficiente. Buscamos la excelencia a nivel de gestión, teniendo siempre en cuenta nuestra prioridad: satisfacer y la atender personalmente todas las necesidades de cada uno de nuestros clientes. 

                </p>
                
                
            </div>
        </div>
    </div>
    <div class="row boxes-destinos">
        
    
    
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/duerming-aldeaduero/duerming-aldeaduero-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Duerming Aldeaduero</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Salamanca, Castilla y León</p>

                        <a href="/hoteles/espana/castilla-y-leon/salamanca/oca-hotel-duerming-aldeaduero/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/justo/justo-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Justo</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sanxenxo, Pontevedra</p>

                        <a href="/hoteles/espana/pontevedra/sanxenxo/oca-justo/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                     
                    
                    
                     
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/san-vicente/san-vicente-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>San Vicente</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">O Grove, Pontevedra</p>

                        <a href="/hoteles/espana/pontevedra/o-grove/oca-san-vicente/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/vila-de-sarria/vila-de-sarria-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Vila de Sarria</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sarria, Lugo</p>

                        <a href="/hoteles/espana/lugo/sarria/oca-villa-de-sarria/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/cruceiro-do-galo/cruceiro-do-galo-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Cruceiro do Galo</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-apartamentos-cruceiro-do-galo/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/sete-artes/sete-artes-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Sete Artes</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-sete-artes/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                      
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/bolera-pico/bolera-pico-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Bolera Pico</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sanxenxo, Pontevedra</p>

                        <a href="/hoteles/espana/pontevedra/sanxenxo/oca-portonovo-pico2/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/portonovo-pico/portonovo-pico-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Portonovo Pico</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sanxenxo, Pontevedra</p>

                        <a href="/hoteles/espana/pontevedra/sanxenxo/oca-portonovo-pico/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/sea-view-viveiro/sea-view-viveiro-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Sea View Viveiro</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Viveiro, Lugo</p>

                        <a href="/hoteles/espana/lugo/viveiro/oca-apartamentos-seaview-viveiro/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/casa-reales/casa-reales-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Casa Reales</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-casas-reales/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/sanxenxo/sanxenxo-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Sanxenxo</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sanxenxo, Pontevedra</p>

                        <a href="/hoteles/espana/pontevedra/sanxenxo/oca-sanxenxo-residence/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/chalets-aldeaduero/chalets-aldeaduero-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Chalets Aldeaduero</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                    </div>
                        <p class="color-blanco font-light txt-130">Salamanca, Castilla y León</p>

                        <a href="/hoteles/espana/castilla-y-leon/salamanca/oca-chalets-rurales-aldeaduero/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        
        </div>
</section>

