<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Agentes")?></h3>
                
                <p>
                    En <strong>Oca Hotels</strong> trabajamos constantemente para mejorar la relación con nuestros colaboradores, es por ello que mejoramos nuestro área de acceso para Agentes de Viajes. </p>
                <p>
                    A través de esta página Web y mediante un rápido y sencillo proceso, podrá realizar reservas (según disponibilidad) y confirmarlas al momento.</p>
                <p>
                    Todas las reservas efectuadas supondrán el pago del importe de su estancia a través de tarjeta de crédito o transferencia bancaria. </p>
                <p class="pdflink"><a href="https://secure.neobookings.com/professionals?id=gN:F7FyTDNnCA92FkWQUHg&uid=s57474" target="_blank" title="Acceso profesionales">ACCESO A PROFESIONALES</a>
                  </p>
               
                
                
            </div>
        </div>
    </div>
    
</section>