<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Canal denuncia")?></h3>
                
                <p>The complaint channel is a communication platform which allows our Hotel chain detect any kind of irregularities, allowing us to ensure compliance with our values and principles.</p>

                <p>Its aim is to facilitate employees, suppliers and customers confidentially inform about illicit misbehaviour, irregularities or vulnerations of the code of behaviour as well as report any inappropriate event and that threatens our Chain and/or its stakeholders.</p>

                <p>OCA Hotels, through the role of the Compliance Officer -external to the company- guarantees the maximum level of confidentiality during all the process, without prejudice to the legal obligations of the complainant, and the safeguard of those people or organizations who are unjustly or in bad faith reported.</p>

                <p>The Chain guarantees the protection of those persons -that use this channel in good faith- against any kind of discrimination and/or penalty. Employees, suppliers and customers will be able to report any kind of detected irregularity and/or criminal act by using the attached online form, which will be directly sent to the Compliance Officer.</p>

                <p>All reports received will be analyzed and investigated, if appropriate, by the Compliance Officer, and transmitted to the Chain Direction Committee with the objective of taking timely and appropriate steps in order to repair the detected deficiencies, such steps will also be subject to the appropriate supervision.</p>
                
                
                  <div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
            <!-- BEGIN Podio web form -->
<script src="https://podio.com/webforms/20063430/1362820.js"></script>
<script type="text/javascript">
  _podioWebForm.render("1362820")
</script>
<noscript>
  <a href="https://podio.com/webforms/20063430/1362820" target="_blank">Por favor, rellena el formulario</a>
</noscript>

<!-- END Podio web form -->






            </div>
        </div>
    </div>
    
</section>