<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Canal denuncia")?></h3>
                
                <p>El Canal Denuncia es una plataforma de comunicación  que permite a nuestra Cadena detectar irregularidades de todo tipo permitiendo de esta forma velar por nuestros valores y principios.</p>

                <p>Su finalidad es facilitar  a empleados, proveedores y clientes  informar de manera confidencial sobre conductas ilícitas, irregularidades o vulneraciones de códigos de conducta  así como denunciar cualquier hecho improcedente y que atente contra nuestra Cadena o/y sus grupos de interés.</p>

                <p>OCA Hotels, a través de la figura del  Responsable de Compliance (Compliance Officer), -externo a la Cadena-  garantiza la máxima confidencialidad en todo el proceso, sin perjuicio de la obligaciones legales del denunciante y  la salvaguardia de aquellas personas u organizaciones denunciadas de manera injusta o mala fe.</p>

                <p>La Cadena garantiza la protección de aquellas  personas -que de buena fe usen este canal- contra cualquier discriminación y/o penalización. Empleados, proveedores y clientes podrán reportar cualquier irregularidad y/o hecho delictivo detectado realizándose dicha comunicación mediante el  formulario online adjunto, que será remitido de forma directa al Responsable de Compliance.</p>

                <p>Todas las denuncias recibidas serán analizadas e investigadas, si procede, por el Responsable de Compliance, y comunicadas al Comité de Dirección de la Cadena al objeto de que el mismo tome las medidas oportunas para la subsanación de las deficiencias detectadas, medidas que serán objeto igualmente del correspondiente seguimiento.</p>
                
                
                  <div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
            <!-- BEGIN Podio web form -->
<script src="https://podio.com/webforms/20063430/1362820.js"></script>
<script type="text/javascript">
  _podioWebForm.render("1362820")
</script>
<noscript>
  <a href="https://podio.com/webforms/20063430/1362820" target="_blank">Por favor, rellena el formulario</a>
</noscript>

<!-- END Podio web form -->






            </div>
        </div>
    </div>
    
</section>