<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Empresas")?></h3>
                
                <p>
                    Principales ventajas para empresas:</p>
                <ul><li>
                        Servicio personalizado.</li>
                    <li>Plantear tarifas y condiciones especiales.</li>
                    <li>Departamento de Atención al Cliente. </li>
                </ul>
                <p>
                    Oca Hotels cuenta con ventajas especiales para las empresas colaboradoras, ofreciendo además un servicio personalizado y adaptado a sus necesidades.</p>
                <p>No dude en contactar con nuestro departamento comercial para estudiar las necesidades de su empresa y plantearle tarifas y condiciones especiales. </p>
                <p>
Para mejorar el servicio y la atención que prestamos a nuestros clientes de empresa ponemos a su disposición el Departamento de Atención al Cliente, que resolverá cualquier duda que tenga. 

                </p>
                
                
            </div>
        </div>
    </div>
    
</section>