<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Empresas")?></h3>
                
                <p>
                   Main advantages for companies:</p>
                <ul><li>
                       Personalized service.</li>
                    <li>To suggest rates and special conditions.</li>
                    <li>Customer service department.</li>
                </ul>
                <p>
                   Oca Hotels has special advantages for collaborating companies, offering in addition a personalized services and tailored to your needs.</p>
                <p>Do not hesitate to contact our commercial department to study your company’s needs  and suggest you rates and special conditions.</p>
                <p>
In order to improve our attentive and careful attitude towards our business customers we put at your disposal our Customer Service Department, that will solve any doubt you may have. 

                </p>
                
                
            </div>
        </div>
    </div>
    
</section>