<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs1-2">
                <h3>LEGAL NOTICE AND GENERAL TERMS AND CONDITIONS FOR USE AND ACCESS OF <a href="http://www.ocahotels.com/">WWW.OCAHOTELS.COM</a></h3>
    <p><br/>
    </p>
    <p>INVERSIONES HOSTELERAS DE GALICIA, S.L., with Company Tax Code B36348217 and business address C/ Miguel Ferro Caaveiro, s/n, 15.703, Santiago de Compostela (A Coruña), registered in Pontevedra Commercial Registry (Volume 2416, Book 2416, Folio 68, Page PO-24980), puts at the disposal of our users and visitors the access and use of the web and informs them of the implications and use conditions, as well as our Personal Data Protection Policy, in case that you willingly facilitate to Oca Hotels any personal information needed in order to access areas contents or services. </p>
    <p>Last version of the General Conditions could always be consulted whenever you wish at <a href="http://www.ocahotels.com/">www.ocahotels.com</a> (hereinafter &ldquo;the Web&rdquo;). If the user does not accept current conditions, they must refrain themselves from entering the Web and/or using its contents and/or services. </p>
    <p><br/>
    </p>
    <h3>SUBJECT OF CONDITIONS</h3>
    <p><br/>
    </p>
    <p>Oca Hotels facilitates to users and visitors the access to our various contents and services disclosed at any given time by Oca Hotel or by third parties content providers and/or services hired by the Hotel.</p>
    <p><br/>
    </p>
    <p>Oca Hotels reserves the right to unilaterally modify the content and configuration of the Web including General Terms of Access and Use. </p>
    <p><br/>
    </p>
    <h3>CONDITIONS OF ACCESS AND USE, ACCEPTANCE AND COST-FREE STATUS</h3>
    <p><br/>
    </p>
    <p>Users acknowledge and accept that at any given moment, Oca Hotels may interrupt, deactivate, and/or cancel any of the Contents and/or Services included on the Web. </p>
    <p>The provision of informative services by the Web are cost-free for users except on the Web sections or services in which the contrary is specified. </p>
    <p><br/>
    </p>
    <h3>USER REGISTRATION</h3>
    <p>In order to access certain services, passwords will be needed. Users will be the only responsibles for the use of said passwords. Users commit to immediately inform Oca Hotels of any unauthorised use of passwords, loss, theft or mislaying, and their knowledge of a possible improper and/or unauthorised use. All information users facilitate must be truthful and authentic, and it is their responsibility to update said information. </p>
    <p><br/>
    </p>
    <h3>USE OF CONTENTS AND SERVICES</h3>
    <p><br/>
    </p>
    <p>Contents, services, passwords and other means at user&rsquo;s disposal must be used according to current legislation, the general conditions here manifested, the moral, good customs generally accepted and public order. Users must abstain from using different means or procedures to the ones specified on the Web, or even the same if it is used to illicit and/or forbidden purposes or to damage the interests of Oca Hotels or third parties. Users must indemnify Oca Hotels for any damage, loss or expense in which Oca Hotels may fall victim to due to illicit and harmful acts that users commit and may damage, disable and deteriorate the Web. </p>
    <p><br/>
    </p>
    <p>The web <a href="http://www.ocahotels.com/">www.ocahotels.com</a> uses Cookies. What are cookies? Cookies are small files of data that your explorer may place in your computer when visiting a web on the Internet, indicating thus that you have been there. That is the reason why your browser must be configured to accept said cookies. </p>
    <p><br/>
    </p>
    <h3>EXCLUSION OF GUARANTEES AND RESPONSIBILITIES </h3>
    <p><br/>
    </p>
    <p>Oca Hotels will not be responsible, under all the extent permitted by the current legal system, of the failures, interferences, deficiencies, overloads, interruptions, telephone or telematic breakdowns, disconnections, etc., that may occur in the communications, security systems nor in the possible alterations generated on the computer system, files or electronic documents. It is neither responsible for viruses or any other harmful elements located on the Web or on the services provided by third parties through Oca Hotels&rsquo; Web, or illicit intrusion out of its control. </p>
    <p>Oca Hotels works on the maintenance and update of Web&rsquo;s data regularly, although it declines any kind of responsibility derived from the harm and damages which could be caused by lack of veracity, trustworthiness, accuracy, usefulness and topicality of the contents of its Web. </p>
    <p>Oca Hotel is not responsible of any inadequacy for any kind of purpose and the disappointment caused by expectations of our own content or third parties&rsquo; content on our Web. </p>
    <p>Oca Hotels does not assume any responsibility for the information found on third parties&rsquo; web to which users may access by using links or browsers. Links shown are merely informative and under any circumstance are meant to be a suggestion, invitation or recommendation to visit them. </p>
    <p>Oca Hotel does not assume responsibility either for those services or contact promoted, financed or provided by third parties to users as consequence of the information or services requested.</p>
    <p><br/>
    </p>
    <h3>INTELLECTUAL PROPERTY RIGHTS AND COPYRIGHT</h3>
    <p><br/>
    </p>
    <p>It is expressly forbidden total or partial reproduction, distribution, transformation, modification, public communication or unauthorised use of the contents, graphic design and Oca Hotels&rsquo; Web Codes,under the terms legally arranged, reserving, thus, all rights of intellectual property. Furthermore, all those distinctive designations, domain names, trademarks, or signs of any kind of content on the Web, are protected by Law. </p>
    <p><br/>
    </p>
    <h3>LEGISLATION AND JURISDICTION</h3>
    <p>On a general basis, all relations between Oca Hotels and the Web users and visitors are subjected to Spanish legislation and are under the jurisdiction of Pontevedra Courts and Tribunals.</p>
    <p><br/>
    </p>
    <h3>NOTIFICATIONS</h3>
    <p>Unless otherwise specified, all notifications, requirements, agreements, consents, acceptance, approvals or communications that required accordance with all stated on these General Conditions or that, one way or another, are related to them, must be written down and sent to Oca Hotels by mail to the company&rsquo;s head office and addressed to the Legal Department. </p>
    <p><br/>
    </p>
    <h3>Data Protection. PRIVACY POLICY</h3>
    <p><br/>
    </p>
    <p>As stipulated in the article 5 on the Law 15/1999 on the 13th of December on the Protection of Personal Data, Inv. Hosteleras de Galicia S.L. informs: </p>
    <p>All data required make up the minimum indispensable in order to be able to accomplish the hired service, and under any given circumstance will be subject to any other use different from the one requested, nor will they be handed over to third parties, unless it is indispensable to accomplish the hired service, being thus solely used for the proper execution of the hired service. </p>
    <p>In any case, users have the right to execute the rights of access, opposition, cancellation or rectification are protected. In order to exercise these rights you may send an e-mail to <a href="mailto:opd@ocahotels.es">opd@ocahotels.es</a>.</p>
    <p><br/>
    </p>
    <h3>REGISTRY DETAILS</h3>
    <p>Commercial Registry of Pontevedra (Volume 2416, Book 2416, Folio 68, Page PO-24980).</p>
            </div>
        </div>
    </div>
    
</section>