<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Inscripción Torneo de Golf")?></h3>
                
                <p>Por favor, rellene este formulario para inscribirse a uno de los Torneos de Golf</p>
                
                
                  <div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
               <!-- BEGIN Podio web form -->
<script src="https://podio.com/webforms/19001877/1280263.js"></script>
<script type="text/javascript">
  _podioWebForm.render("1280263")
</script>
<noscript>
  <a href="https://podio.com/webforms/19001877/1280263" target="_blank">Por favor, rellena el formulario</a>
</noscript>

<!-- END Podio web form -->




            </div>
        </div>
    </div>
    
</section>