<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3>OCA Hotels</h3>
                
                <h4>Mission</h4>
 
                <p>OCA Hotels intends to contribute to our society by providing tangible benefits, always offering hotel services of excellent quality, innovative and efficient based on the development of our human capital, excellence of management, and always aiming to obtain full satisfaction of our customers. </p>
 
<h4>Vision</h4>
 
<p>OCA Hotels aspires to become a chain whose organization is leader in sustainable and responsible management of tourists establishments in the North East of Spain.</p>
<p>People are a key part of our vision and our employees work very hard every day so that all our customers receive, at all times, the best service. As consequence, each stay is a challenge for improvement. The needs of our customers vary from time to time and because of that we assume that the process of constant innovation is essential.</p>
<p>This way we are able to preserve the competitiveness as business group.</p>
 
<h4>Values</h4>
 
<p>All the people who make up OCA Hotels have the will to proclaim our commitment to this project, which we will lead to success from humbleness and simplicity, closeness to our customers, to the employee, to the shareholder and to all Society surrounding us. </p>
<p>We also adopt as own value a deep respect and protection of the environment, contributing thus to the sustainable development of our community.</p><p>As organization, we will be efficient without losing our capacity of response and we will make sure humanness is always present in our management approach. </p>
<p>OCA Hotels, according to the Resolution 58/4 of the General Assembly of the 31st of October, 2003 of “United Nations Convention Against Corruption” decides to take on as its own and abide by the recommendation of above mentioned document about the Private Sector, recognised by Article 12, whose requirements, adjusted to the ethical management of our Hotel Chain, are here described:</p>
<ul>
    <li>1. OCA Hotels, as a private company, will be guided by the fundamental principles of good governance and ethical management taking measures in order to prevent corruption and improve its process and accounting and auditing standards. </li>
    <li>2. Measures taken in order to achieve these objectives may consist, among other things, on:
        <ul>
            <li style="font-size: 0.8em;">a) To promote cooperation between our Hotel Chain and the law enforcement agencies.</li>
            <li style="font-size: 0.8em;">b) To promote policy-making of norms and procedures directed to safeguard our integrity as an independent private entity, including codes of conduct for the appropriate, honorable and proper exercise of commercial activities and that of all appropriate professions and to prevent conflicts of interests, as well as to promote the use of good business practices between our company and those directly or indirectly depending on the various public administrations. </li>
            <li style="font-size: 0.8em;">c) To promote transparency in our management including, when appropriate, measures with regard to the identity of legal and natural persons involved in the establishment and management of companies. </li>
            <li style="font-size: 0.8em;">d)To prevent the improper use of administrative procedures that regulate private entities, including those procedures related to grants and licenses by public authorities aimed at commercial activities.</li>
            <li style="font-size: 0.8em;">e)To guard that OCA Hotels, according to its size and structure, has enough intern accounting controls to prevent and detect those acts associated to corruption, and that our accounts and financial statements are subject to the appropriate and thorough audit and certification processes.</li>
        </ul>
        
    </li>
    <li>3.  In order to prevent corruption, OCA Hotels will take the necessary steps, in accordance with its internal functioning and regulations related to the maintenance of books and records, disclosure of financial statements and the audit and accountability norms, in order to ban the following acts made in order to commit any of the offences established in accordance with this Convention:
        <ul>
            <li style="font-size: 0.8em;">a) The establishment of off-the-books accounts.</li>
            <li style="font-size: 0.8em;">b) The making of off-the-books or inadequately identified transactions.</li>
            <li style="font-size: 0.8em;">c) Recording of non-existing expenditure.</li>
            <li style="font-size: 0.8em;">d) The entry of liabilities with incorrect identification of their objects.</li>
            <li style="font-size: 0.8em;">e) The use of false documents.</li>
            <li style="font-size: 0.8em;">f) he intentional destruction of bookkeeping documents earlier that foreseen by the law.</li>
        </ul>
    
    </li>
</ul>







 

                
                
            </div>
        </div>
    </div>
    
</section>