<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3>OCA Hotels</h3>
                
                <h4>Misión</h4>
 
                <p>Desde OCA Hotels pretendemos aportar a nuestra comunidad beneficios tangibles, ofertando en todo momento servicios hoteleros de Calidad, innovadores y eficientes basados en el desarrollo de nuestro capital humano, la excelencia en gestión y siempre buscando la plena satisfacción de nuestros clientes.</p>
 
<h4>Visión</h4>
 
<p>En OCA Hotels aspiramos a que nuestra cadena sea una organización líder en la gestión sostenible y responsable de establecimientos turísticos, en el noroeste peninsular.</p>
<p>Las personas son claves en nuestra visión, y las que trabajan en nuestros hoteles se esfuerzan día a día para conseguir que todos y cada uno de nuestros clientes reciban en todo momento el mejor de los servicios haciendo, de cada estancia un reto de superación.</p>
<p>Las necesidades de nuestros clientes varían con el tiempo, por lo que asumimos como imprescindible el proceso permanente de Innovación, que nos permita mantener en el tiempo nuestra competitividad como grupo empresarial.</p>
 
<h4>Valores</h4>
 
<p>Las personas que componemos OCA Hotels queremos proclamar nuestro compromiso con este proyecto que llevaremos al éxito desde la humildad y la sencillez, la cercanía al cliente, al empleado, al accionista y a toda la Sociedad que nos rodea.</p>
<p>Igualmente, asumimos como valor propio el profundo Cuidado y respeto por el Medio Ambiente contribuyendo de esta forma al Desarrollo Sostenible de nuestra comunidad.</p>
<p>Como organización, seremos eficientes sin perder nuestra capacidad de respuesta y haremos que la Humanidad esté siempre presente en nuestra línea de gestión.</p>
 
<p>OCA Hotels, en concordancia con la Resolución 58/4 de la Asamblea General, de 31 de octubre de 2003 <strong>Convención de las Naciones Unidas contra la Corrupción</strong> decide asumir como propias y cumplir las recomendaciones del citado documento vinculadas al <strong>Sector Privado, recogidas en su Artículo 12</strong>, cuyos requisitos, adaptados a la gestión ética de nuestra Cadena Hotelera, se recogen a continuación:</p>
<ul>
    <li>1. OCA Hotels, como compañía privada se regirá de conformidad con los principios fundamentales de la buena gobernanza y gestión ética adoptando medidas para prevenir la corrupción y mejorar sus procesos y normas contables y de auditoría.</li>
    <li>2. Las medidas que se adopten para alcanzar esos fines podrán consistir, entre otras cosas, en:
        <ul>
            <li style="font-size: 0.8em;">a) Promover la cooperación entre nuestra Cadena Hotelera y los los organismos encargados de hacer cumplir la ley</li>
            <li style="font-size: 0.8em;">b) Promover la formulación de normas y procedimientos encaminados a salvaguardar nuestra integridad como entidad privada independiente, incluidos códigos de conducta para el correcto, honorable y debido ejercicio de las actividades comerciales y de todas las profesiones pertinentes y para la prevención de conflictos de intereses, así como para la promoción del uso de buenas prácticas comerciales entre nuestra empresa y aquellas dependientes directa o indirectamente de las diferentes administraciones públicas</li>
            <li style="font-size: 0.8em;">c) Promover una transparencia en nuestra gestión incluyendo, cuando proceda, medidas relativas a la identidad de las personas jurídicas y naturales involucradas en el establecimiento y la gestión de empresas;</li>
            <li style="font-size: 0.8em;">d) Prevenir la utilización indebida de los procedimientos administrativos que regulan a las entidades privadas, incluidos los procedimientos relativos a la concesión de subsidios y licencias por las autoridades públicas para actividades comerciales;</li>
            <li style="font-size: 0.8em;">e) Velar porque OCA Hotels, conforme a su estructura y tamaño, disponga de suficientes controles contables internos para ayudar a prevenir y detectar los actos asociaddos a l corrupción, y por que las cuentas y los estados financieros de nuestra empresa estén sujetos a procedimientos apropiados y rigurosos de auditoría y certificación.</li>
        </ul>
        
    </li>
    <li>3. A fin de prevenir la corrupción, OCA Hotels adoptará las medidas que sean necesarias, de conformidad con su funcionamiento interno y reglamentos relativos al mantenimiento de libros y registros, la divulgación de estados financieros y las normas de contabilidad y auditoría, para prohibir los siguientes actos realizados con el fin de cometer cualesquiera de los delitos tipificados con arreglo a la presente Convención:
        <ul>
            <li style="font-size: 0.8em;">a) El establecimiento de cuentas no registradas en libros.</li>
            <li style="font-size: 0.8em;">b) La realización de operaciones no registradas en libros o mal consignadas.</li>
            <li style="font-size: 0.8em;">c) El registro de gastos inexistentes.</li>
            <li style="font-size: 0.8em;">d) El asiento de gastos en los libros de contabilidad con indicación incorrecta de su objeto.</li>
            <li style="font-size: 0.8em;">e) La utilización de documentos falsos.</li>
            <li style="font-size: 0.8em;">f) La destrucción deliberada de documentos de contabilidad antes del plazo previsto en la ley.</li>
        </ul>
    
    </li>
</ul>







 

                
                
            </div>
        </div>
    </div>
    
</section>