<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/a-coruna/001-hoteles-en-a-coruna.jpg')"></div>
                   </div>
               </div>
         

    <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/a-coruna/002-hoteles-en-a-coruna.jpg')"></div>
                   </div>
               </div>

    <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/a-coruna/003-hoteles-en-a-coruna.jpg')"></div>
                   </div>
               </div>

            
            <div class="carousel-caption">
                <h1 class="text-uppercase ">Hoteles en A Coruña</h1>
                <h2 style="font-size:1.3em !important; font-weight: 300;">Encuentre alojamiento en A Coruña, Galicia</h2>
              
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="breadcrumb pd-l-0"><a href="/">OCA HOTELS</a> > <a href="/destinos">DESTINOS</a> > A CORUÑA</div>
           <div class="ol-xs-12 col-xs-push-0  col-md-12 col-lg-6">
              
               <h3 style="line-height: inherit">Disfrute de su viaje a A Coruña en uno de los confortables hoteles y apartamentos de OCA Hotels y Duerming.</h3>
               
                 <h4 style="line-height: inherit;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h4>
                
                <p> 
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <br>
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-lg-5 col-lg-push-1"> 
  
        
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 110px;background-image: url('/images/hoteles/puerta-del-camino/puerta-del-camino-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 110px;height: 110px;">

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-puerta-del-camino/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Puerta del Camino</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>
                       
                    </div>
 
                </div>
                
            </div>
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 110px;background-image: url('/images/hoteles/insua-costa-da-morte/insua-costa-da-morte-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 110px;height: 110px;">
                        <a href="/hoteles/espana/a-coruna/cee/oca-insua/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Insua Costa da Morte</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Cee</h5>
                                           </div>
                 </div>
                            </div>
                
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 110px;background-image: url('/images/hoteles/cruceiro-do-galo/cruceiro-do-galo-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 110px;height: 110px;">
                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-apartamentos-cruceiro-do-galo/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Cruceiro do Galo</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>
                                           </div>
                 </div>
                            </div>
                
                       <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 110px;background-image: url('/images/hoteles/sete-artes/sete-artes-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 110px;height: 110px;">
                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-sete-artes/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Sete Artes</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                                                                        
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>
                                           </div>
                 </div>
                            </div>

                
                  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 110px;background-image: url('/images/hoteles/casa-reales/casa-reales-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 110px;height: 110px;">
                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-casas-reales/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Casa Reales</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                                                                        
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>
                                           </div>
                 </div>
                            </div>
                
                
                     
                     
                       
                        
    
             

               </div>
          
           
    </div>
    </div>
</section>



<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



