<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/augas-santas/golf/0001-golf.jpg')"></div>
                   </div>
               </div>
         

    <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/palacio-llorea/golf/0001-golf-palacio-llorea.jpg')"></div>
                   </div>
               </div>
            
            <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/augas-santas/inicio/0006-golf.jpg')"></div>
                   </div>
               </div>


            
            <div class="carousel-caption">
                <h1 class="text-uppercase ">Hoteles para jugar al golf</h1>
                <h2 style="font-size:1.3em !important; font-weight: 300;">Hoteles OCA junto a campos de golf en Lugo y Gijón.</h2>
              
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="breadcrumb pd-l-0"><a href="/">OCA HOTELS</a> > <a href="/experiencias">EXPERIENCIAS</a> > GOLF</div>
           <div class="ol-xs-12 col-xs-push-0  col-md-12 col-lg-6">
              
               <h3 style="line-height: inherit">Juega al golf durante tus vacaciones.</h3>
               
                 <h4 style="line-height: inherit;">Oca Augas Santas y Palacio de la Llorea, ponen al servicio de los aficionados al golf una amplia oferta deportiva gracias a su acceso a dos campos de golf únicos
</h4>
                
               <p>
Los 18 hoyos de Augas Santas entre los que se dividen los más de 5.000 metros de campo, gozan de un relieve prácticamente llano y unos greens francos y bien protegidos.</p><p>

                   Un campo de golf único que disfrutará al máximo gracias a las instalaciones y los servicios que ofrece el Club de Golf Augas Santas, como su cancha de prácticas, putting-green, zona de aproach con bunker de prácticas, tienda de golf, escuela deportiva, alquiler de equipo, e incluso clases privadas a manos de profesionales.</p><p>Palacio de la Llorea cuenta con un acuerdo de colaboración con Campo de Golf de La Llorea, lo que permite a nuestros clientes tener acceso completo a los 18 hoyos de este campo de golf ubicado en una rasa costera a 100 metros sobre el nivel del mar, ofreciendo unas vistas inmejorables mientras disfruta de un fantástico día de golf.</p>
           
                    <br>
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-lg-5 col-lg-push-1"> 
  
        
          
                
     
                
                
                
                
              
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 210px;background-image: url('/images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 210px;height: 210px;">

                        <a href="/hoteles/espana/asturias/gijon/oca-palacio-llorea/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Palacio de la Llorea</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Gijón</h5>
                             <a href="/destinos/asturias/"><h5 class="color-blanco font-light txt-100 mg-t-0">Asturias</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
                
               
                
                
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 210px;background-image: url('/images/hoteles/augas-santas/augas-santas-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 210px;height: 210px;">

                        <a href="/hoteles/espana/lugo/panton/oca-augas-santas/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Augas Santas</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Pantón</h5>
                              <a href="/destinos/lugo/"><h5 class="color-blanco font-light txt-100 mg-t-0">Lugo</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
                 
                
                
                     
                     
                       
                        
    
             

               </div>
          
           
    </div>
    </div>
</section>



<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



