<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs1-2">
                <h3><?php echo _("Sala de prensa")?></h3>
                
                 <h4>
                     Mass Media Contact</h4>
                <p>e-mail: <a href="mailto:marketing@ocahotels.es">marketing@ocahotels.es</a></p>
                <p>Telf: 951 968 124</p>

               
                
                
                
            </div>
        </div>
    </div>
    
</section>