<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles-camino-de-santiago/hoteles-camino-de-santiago-home.jpg')"></div>
                   </div>
               </div>
         
            
            <div class="carousel-caption">
                <h2 class="text-uppercase txt-220"><?php echo $titulo?></h2>
                <h3 style="font-weight: 300">Encuentre su hotel en el Camino de Santiago</h3>
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
           <div class="ol-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2 text-center">
              
               <h2 class="color-accion" style="line-height: inherit">Disfrute de un Camino de Santiago durmiendo en Hoteles Oca</h2>
               
                 
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2"> 
                <h4 style="line-height: inherit;">Gracias a nuestro programa OCA EN EL CAMINO, los peregrinos del Camino de Santiago gozan de las siguientes ventajas extra durante su ruta a través de Galicia:</h4>
                <b>
                <p> 
                    Servicio de lavandería con tarifa especial<br>
                    Preparación de bolsa de picnic<br>
                    Libro de información para peregrinos<br>
                    Servicio de masajistas, bajo demanda<br>
                    OCA BIKE SERVICE: zona para guardar las bicicletas con espacio para su limpieza y mantenimiento. Servicio de transporte de bicicletas bajo demanda<br>
                    Menú especial para peregrinos, en el propio hotel o en restaurante próximo<br>
                    Servicio de traslado de mochilas personas</b></p>
                    <br>
                    <a href="https://podio.com/webforms/19688648/1334904?fields[en-que-esta-interesad]=1" target="_blank" class="pdflink"><h4>SOLICITAR INFORMACIÓN</h4></a>
               </div>
          
           
    </div>
    </div>
</section>


<div id="contenedor-boxes" style="display: block;"><section class="bck-color-blanco">
    <div class="container-fluid ">
        
        <div class="row boxes-destinos">
        
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/puerta-del-camino/puerta-del-camino-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Puerta del camino</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-puerta-del-camino/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/santo-domingo-plaza/santo-domingo-plaza-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Santo Domingo Plaza</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Oviedo, Asturias</p>

                        <a href="/hoteles/espana/asturias/oviedo/oca-santo-domingo-plaza/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Vila de Allariz</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Allariz, Ourense</p>

                        <a href="/hoteles/espana/ourense/allariz/oca-allariz/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/insua-costa-da-morte/insua-costa-da-morte-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Insua Costa da Morte</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Cee, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/cee/oca-insua/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/rio-pambre/rio-pambre-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Rio Pambre</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Palas de Reis, Lugo</p>

                        <a href="/hoteles/espana/lugo/palas-de-reis/oca-rio-pambre/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/vila-de-sarria/vila-de-sarria-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Vila de Sarria</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Sarria, Lugo</p>

                        <a href="/hoteles/espana/lugo/sarria/oca-villa-de-sarria/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/cruceiro-do-galo/cruceiro-do-galo-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Cruceiro do Galo</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-apartamentos-cruceiro-do-galo/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/sete-artes/sete-artes-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Sete Artes</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-sete-artes/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/casa-reales/casa-reales-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Casa Reales</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-casas-reales/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        
        </div>
        
    </div>
</section>
</div>
<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



