<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles-con-wellness/hoteles-con-wellness-home.jpg')"></div>
                   </div>
               </div>
         
            
            <div class="carousel-caption">
                <h2 class="text-uppercase txt-220"><?php echo $titulo?></h2>
                <h3 style="font-weight: 300">Celebre la boda de sus sueños con Oca Hotels</h3>
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
           <div class="ol-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2 text-center">
              
               <h2 class="color-accion" style="line-height: inherit">Sumérjase en un profundo estado de relajación con los servicios wellness de Oca Hotels</h2>
               
                 
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2"> 
                <h4 style="line-height: inherit;">Entre nuestros hoteles encontrará una gran oferta de spa y balnearios, entre los que se ofrecen algunos de los mejores tratamientos wellness de España<br><br>(Finalistas en los premios Wellness & Spa Experience, como Mejor Balneario y Mejor Técnica Termal o Wellness).</h4>
                
                <p> Elija entre sumergirse en el poder sanador de las aguas minerales de nuestros balnearios o disfrutar de infinidad de tratamientos spa que le sumirán en un profundo estado de relajación, ambos tratamientos perfectos para dejar atrás los problemas y la rutina del día a día. </p>
                <p>
                   Nuestros balnearios y spas están equipados con lo último en equipamiento:  
                </p>
            
                <h4 style="line-height:inherit" class="text-center">
                    ·Baños de burbuja e hidromasaje ·Chorro termal ·Piscina activa ·Cuellos de cisne ·Camas de agua ·Cabina de hielo ·Sauna ·Baño turco ·Chorros a presión ·Cascadas…</h4><br>
              <p>
                  Nuestros masajes, estiramientos y diversos tratamientos (faciales, envolvimientos de lino y algas…) cierran la mejor oferta en descanso que encontrará usted en la zona.  
                </p>
            
            <br>
                    <a href="https://podio.com/webforms/19688648/1334904?fields[en-que-esta-interesad]=3" target="_blank" class="pdflink"><h4>SOLICITAR INFORMACIÓN</h4></a></div>
          
           
    </div>
    </div>
</section>


<div id="contenedor-boxes" style="display: block;"><section class="bck-color-blanco">
    <div class="container-fluid ">
        
        <div class="row boxes-destinos">
        
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/augas-santas/augas-santas-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Augas Santas</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Pantón, Lugo</p>

                        <a href="/hoteles/espana/lugo/panton/oca-augas-santas/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Palacio de la Llorea</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Gijón, Asturias</p>

                        <a href="/hoteles/espana/asturias/gijon/oca-palacio-llorea/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Vila de Allariz</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Allariz, Ourense</p>

                        <a href="/hoteles/espana/ourense/allariz/oca-allariz/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/rio-pambre/rio-pambre-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Rio Pambre</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Palas de Reis, Lugo</p>

                        <a href="/hoteles/espana/lugo/palas-de-reis/oca-rio-pambre/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        
        </div>
        
    </div>
</section>
</div>
<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



