<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/partners/0001-ocapartners.jpg')"></div>
                   </div>
               </div>
         
            
            <div class="carousel-caption">
                <h2 class="text-uppercase txt-220"><img src="https://ocahotels.com/images/partners/oca-partners.png" alt="OCA PARTNERS" class="img-responsive" style="display: block; margin: 0 auto;"></h2>
              
            </div>
            
        </div>
        
      

    </div>
    
</header>

<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
               <h3>OCA Partners</h3>
                
                <p>
                   At Oca Hotels we constantly work to improve our relations with our collaborators, that is why we improve our access area for Travel Agents. </p>
                <p>
                  By using this Web and through a fast and simple process, you will make reservations (under availability) and confirm them straight away. </p>
                <p>
                   All bookings made must be paid via credit card or bank transfer. </p>
                <p class="pdflink"><a href="https://secure.neobookings.com/professionals?id=gN:F7FyTDNnCA92FkWQUHg&uid=s57474" target="_blank" title="Acceso profesionales">PROFESSIONALS ACCESS</a>
                  </p>
               
                
                
            </div>
        </div>
    </div>
    
</section>