<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/home/bonos.jpg')"></div>
                   </div>
               </div>
         
            
            <div class="carousel-caption">
                <h2 class="text-uppercase txt-220"><?php echo $titulo?></h2>
                <h3 style="font-weight: 300">Regala experiencias inolvidables en Oca</h3>
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 container">
    <div class=" content-interior">
        <div class="row">
              <div class="col-xs-12 text-center mg-b-30">
                
              
                <div class="col-xs-8 col-xs-push-2 col-sm-6 col-sm-push-3 col-md-3 col-md-push-0 col-lg-3 col-lg-push-0 text-center"> <h1> <img src="https://ocahotels.com/images/bonos-regalo.png" class="img-responsive" title="Oca Hoteles Bonos Regalo"></h1></div>
                <div class="col-xs-12 col-sm-10 col-sm-push-1 col-md-8 col-md-push-1 col-lg-8 col-lg-push-1 text-left"><h2>Disfruta de descuentos exclusivos y ofertas especiales en Oca Hotels</h2>
                 
                 <h3>Aprovechas estas ocasiones especiales de alojamiento y combínalas con menús especiales, circuitos de SPA, masajes, tratamientos corporales, <em>green fee</em> de golf... </h3>
                </div>
               
                  </div>
            <div class="col-xs-12">
               
                
                 
                 
              <section class="bck-color-blanco">
                  
                  <!-- UNA CAJA POR CADA HOTEL CON BONO -->
    
                
                  
                  
    <!--<div class="container-fluid ">
        
         <div class="row boxes-destinos">
          
             
            <div class="col-xs-12 col-sm-12 col-md-8 col-md-push-2 col-lg-4 col-lg-push-0">
                <div class="text-center back-image5" style="margin-bottom:20px !important;  background-image: url('<?php echo $ROOT ?>images/hoteles/augas-santas/augas-santas-home.jpg')">

                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3></h3>
                        <p class='color-blanco font-light txt-150'></p>
                        
                        
                        <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=3&idPT=3,1,6&head=0" class="btn btn-primary-box mg-t-50" style="top:0;" target="_blank"><?=_("BONOS REGALO")?><br>Augas Santas</a>
                    </div>

                </div>
                
            </div>
             
             
                <div class="col-xs-12 col-sm-12 col-md-8 col-md-push-2 col-lg-4 col-lg-push-0">
                <div class="text-center back-image5" style="margin-bottom:20px !important;  background-image: url('<?php echo $ROOT ?>images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg')">

                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3></h3>
                        <p class='color-blanco font-light txt-150'></p>
                        
                        
                        <a href="https://www.centrotel.es/newCRSUI2/booking/itemsSelectionNoDates.aspx?CRSName=ocahotels&gifts=1&idEstablishmentSRT=1&idPT=3,1,6" class="btn btn-primary-box mg-t-50" style="top:0;" target="_blank"><?=_("BONOS REGALO")?><br>Vila de Allariz</a>
                    </div>

                </div>
                
            </div>
             
             
                <div class="col-xs-12 col-sm-12 col-md-8 col-md-push-2 col-lg-4 col-lg-push-0">
                <div class="text-center back-image5" style="margin-bottom:20px !important;  background-image: url('<?php echo $ROOT ?>images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg')">

                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3></h3>
                        <p class='color-blanco font-light txt-150'></p>
                        
                        
                        <a href="https://www.centrotel.es/newCRSUI2/booking/itemsSelectionNoDates.aspx?CRSName=ocahotels&gifts=1&idEstablishmentSRT=2&idPT=3,1,6&head=0" class="btn btn-primary-box mg-t-50" style="top:0;" target="_blank"><?=_("BONOS REGALO")?><br>Palacio de la Llorea</a>
                    </div>

                </div>
                
            </div>
          
            
        </div>

    </div>-->
    
       <div class="row mg-b-40">
                      <div class="col-xs-10 col-xs-push-1 col-sm-4 col-sm-push-0">
                          <div class="text-center back-image5" style="margin-bottom:20px !important;  background-image: url('<?php echo $ROOT ?>images/hoteles/rio-pambre/rio-pambre-home.jpg'); background-position:center;"></div>                          
                      </div>
                      
                        <div class="col-xs-12 col-sm-6 col-sm-push-1"><h2 class="text-center">BONOS REGALO RÍO PAMBRE</h2><br>
                    
                            <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=6&idPT=7" target="_blank" class="pdflink"><strong>BONOS REGALO</strong></a><br>
                          <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=6&idPT=1,3,6" target="_blank" class="pdflink">BONOS CON ALOJAMIENTO</a>
                                           
                        </div></div>
    
    
    
                  <div class="row mg-b-40">
                      <div class="col-xs-10 col-xs-push-1 col-sm-4 col-sm-push-0">
                          <div class="text-center back-image5" style="margin-bottom:20px !important;  background-image: url('<?php echo $ROOT ?>images/hoteles/rocallaura/rocallaura-home.jpg'); background-position:center;"></div>                          
                      </div>
                      
                        <div class="col-xs-12 col-sm-6 col-sm-push-1"><h2 class="text-center">BONOS REGALO ROCALLAURA</h2><br>
                    
                            <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=5&idPT=7&head=0" target="_blank" class="pdflink"><strong>BONOS REGALO</strong></a><br>
                          <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=5&idPT=3,1,6&head=0" target="_blank" class="pdflink">BONOS CON ALOJAMIENTO</a>
                                           
                        </div></div>
                  
                  
                  <div class="row mg-b-40">
                      <div class="col-xs-10 col-xs-push-1 col-sm-4 col-sm-push-0">
                          <div class="text-center back-image5" style="margin-bottom:20px !important;  background-image: url('<?php echo $ROOT ?>images/hoteles/augas-santas/augas-santas-home.jpg'); background-position:center;"></div>                          
                      </div>
                      
                        <div class="col-xs-12 col-sm-6 col-sm-push-1"><h2 class="text-center">BONOS REGALO AUGAS SANTAS</h2><br>
                    
                            <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=3&idPT=7&head=0" target="_blank" class="pdflink"><strong>BONOS REGALO</strong></a><br>
                          <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=3&idPT=3,1,6&head=0" target="_blank" class="pdflink">BONOS CON ALOJAMIENTO</a>
                                           
                        </div></div>
                  
                  
                  
                   <div class="row mg-b-40">
                      <div class="col-xs-10 col-xs-push-1 col-sm-4 col-sm-push-0">
                          <div class="text-center back-image5" style="margin-bottom:20px !important;  background-image: url('<?php echo $ROOT ?>images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg'); background-position:center;"></div>                          
                      </div>
                      
                        <div class="col-xs-12 col-sm-6 col-sm-push-1"><h2 class="text-center">BONOS REGALO VILLA DE ALLARIZ</h2><br>
                    
                            <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=1&idPT=2,4,5&head=0" target="_blank" class="pdflink"><strong>BONOS REGALO</strong></a><br>
                          <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=1&idPT=3,1,6&head=0" target="_blank" class="pdflink">BONOS CON ALOJAMIENTO</a>
                                           
                        </div></div>
                  
                  
                   <div class="row mg-b-40">
                      <div class="col-xs-10 col-xs-push-1 col-sm-4 col-sm-push-0">
                          <div class="text-center back-image5" style="margin-bottom:20px !important;  background-image: url('<?php echo $ROOT ?>images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg'); background-position:center;"></div>                          
                      </div>
                      
                        <div class="col-xs-12 col-sm-6 col-sm-push-1"><h2 class="text-center">BONOS REGALO PALACIO DE LA LLOREA</h2><br>
                    
                            <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=4&idPT=7&head=0" target="_blank" class="pdflink"><strong>BONOS REGALO</strong></a><br>
                          <a href="https://www.centrotel.es/ocahotels/gifts.asp?idEstablishmentSRT=4&idPT=3,1,6&head=0" target="_blank" class="pdflink">BONOS CON ALOJAMIENTO</a>
                                           
                        </div></div>
    
    
    
</section>
                 
                 

               
                
                
                
            </div>
        </div>
    </div>
    
</section>