;<?php exit(); /* ¡NO tocar esta linea! */?>

;
; [Debug]
;
SQL_ERROR    = no
DEBUG_SQL    = no
SHOW_NOTICES = no

;
;[DIRECTORIES]
;
ROOT = /proyectos/ocahoteles/
EMAILS = /proyectos/ocahoteles/_tmplsEmails/
IMAGES_OLD = /fotos/

;
; [DB]
;
CONNECTION_STRING = 'mysql:host=localhost;dbname=galeriaoouoca;charset=utf8'
HOST     = localhost
DATABASE = galeriaoouoca
USER     = root
PASSWORD = 

;
; [Mails]
;
;noreply
EMAIL_SMTP = "smtp.puraenvidia.com"
EMAIL_USER = "juan@puraenvidia.com"
EMAIL_PORT = "25"
EMAIL_PROTOCOL = ""
EMAIL_PASSWORD = "Mexico6"
EMAIL_FROM_EMAIL = "juan@puraenvidia.com"
EMAIL_FROM_NAME = "Juan"

;
; [OTHERS]
;
TEMPLATE=ocahoteles
