;<?php exit(); /* ¡NO tocar esta linea! */?>

;
; [Debug]
;
SQL_ERROR    = no
DEBUG_SQL    = no
SHOW_NOTICES = no

;
;[DIRECTORIES]
;
ROOT = /
EMAILS = /_tmplsEmails/
IMAGES_OLD = /fotos/

;
; [DB]
;
CONNECTION_STRING = 'mysql:host=galeriaoouoca.mysql.db;dbname=galeriaoouoca;charset=utf8'
HOST     = galeriaoouoca.mysql.db
DATABASE = galeriaoouoca
USER     = galeriaoouoca
PASSWORD = P17Envidia

;
; [Mails]
;

EMAIL_SMTP = "smtp.gmail.com"
EMAIL_USER = "marketing@ocahotels.es"
EMAIL_PORT = "465"
EMAIL_PROTOCOL = "ssl"
EMAIL_PASSWORD = "puraenvidia2017"
EMAIL_FROM_EMAIL = "marketing@ocahotels.es"
EMAIL_FROM_NAME = "Oca Hotels"

;
; [OTHERS]
;
TEMPLATE=ocahoteles
