<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3>Optimice su negocio hotelero: descubra nuestra propuesta de gestión o franquicia</h3>
                
                <h4>Régimen de franquicia:</h4>
                
                <p>
                    Si lo que usted quiere es continuar con la gestión de su establecimiento, pero amparado y respaldado por un grupo hotelero, el proponemos afiliarse en régimen de <strong>FRANQUICIA</strong>.
                El contrato de franquicia le aporta:
                </p>
                <ul>
                    <li>Imagen de marca.</li>
                    <li>Manuales operativos.</li>
                    <li>Apoyo a la gestión diaria.</li>
                    <li>Gestión comercial.</li>
                    <li>Gestión redes sociales y reputación online.</li>
                    <li>Gestión de revenue management.</li>
                    <li>Central de compras.</li>
                    <li>…………………… y mucho más</li>
                </ul>
                    
                <h4>Contrato de Gestión</h4>
 
                <p>Si prefiere desligarse de la gestión directa de su establecimiento, nosotros nos encargamos de la explotación directa, a través de un contrato de <strong>GESTIÓN</strong>.
El contrato de gestión le aporta una gestión total del establecimiento por parte del equipo Oca, usted se olvidará de la operativa y contará con un equipo altamente profesional para la explotación de su establecimiento.
Un equipo humano con amplia experiencia a su disposición, en unas condiciones económicas muy ventajosas. No requerimos inversión inicial alguna, nosotros nos adaptamos a su establecimiento.
Respetamos la exclusividad, no más de un establecimiento por marca en la zona de influencia.
</p>

                
            <p class="mg-t-40">Hable de hotelero a hotelero, contacte directamente con nuestro equipo de expansión y le haremos llegar una propuesta de forma inmediata.</p>
 
<p>Departamento de Expansión:
    <a href="mailto:groupdesk@ocahotels.es"><strong>groupdesk@ocahotels.es</strong></a><br>
T. <a href="tel:981 10 70 05"><strong>981 10 70 05</strong></a> (10,30 a 14,30 horas).</p>
            </div>
        </div>
    </div>
    
</section>