<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3>Optimize your hotel business: discover our management or franchise proposal.</h3>
                
                <h4>Under Franchise:</h4>
                
                <p>
                    If what you want is to continue with the management of your establishment but protected by the support of an hotel chain, we propose you to affiliate to us under a franchise agreement.<br>
               The franchise contract provides you with:
                </p>
                <ul>
                    <li>Brand image.</li>
                    <li>Operational manual.</li>
                    <li>Support to daily management.</li>
                    <li>Commercial management.</li>
                    <li>Management of social media and online reputation.</li>
                    <li>Revenue management.</li>
                    <li>Purchasing centre.</li>
                    <li>…………………… and much more!</li>
                </ul>
                    
                <h4>Management Contract</h4>
 
                <p>If you prefer to dissociate from the direct management of your establishment, we will take charge of the direct exploitation via a MANAGEMENT contract. Said management contract contributes with a total management of the establishment by the Oca team, you will forget about the operating mechanism and will count on a highly qualified team to exploit your establishment. A human team with extensive experience at your disposal, under very profitable economic conditions. We do not require any initial investment, we are the ones adapting to your establishment. We respect exclusiveness; there will be no more than one establishment per brand within the area of influence.
</p>

                
            <p class="mg-t-40">Talk hotelier to hotelier, contact directly with our expansion team and they will immediately send you a proposal.</p>
 
<p>Expansion Department:
    <a href="mailto:groupdesk@ocahotels.es"><strong>groupdesk@ocahotels.es</strong></a><br>
T. <a href="tel:981 10 70 05"><strong>981 10 70 05</strong></a> (10,30 to 14,30 hs).</p>
            </div>
        </div>
    </div>
    
</section>