<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs1-2">
                <h3>PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL. POLÍTICA DE PRIVACIDAD</h3>
                
                <p>Oca Hotels, Oca Termal Hotels y Grand Oca Hotels & Resort son marcas registradas de Inversiones Hosteleras de Galicia S.L. (I.H.G.) con CIF: B36348217 y domicilio en Miguel Ferro Caaveiro S/N. Oficina 1019 - 15707. Santiago de Compostela (A Coruña). Empresa inscrita en el Registro Mercantil dede la provincia de Pontevedra (Tomo 2416, Libro 2416, Folio 68, Hoja PO-24980).</p>
                
                <p>Oca Hotels le informa que de acuerdo con la Ley Orgánica 15/1999, de 13 de diciembre, de protección de datos de carácter personal, los datos que el USUARIO facilite en los formularios de nuestra página web, se incorporarán a los ficheros titularidad de Oca Hotels para ser tratados con la finalidad de gestionar la reserva de plazas hoteleras, así como para la gestión de los abonos al campo de golf del Oca Augassantas Hotel & Spa; el USUARIO tiene la posibilidad de consentir el envío de comunicaciones comerciales relativas a los productos que actualmente o en el futuro ofrezca Oca Hotels. a través de su portal web.</p>

                <p>Para acceder al sitio web de Oca Hotels no es necesario aportar ningún dato.</p>

                <p>Sin embargo, para realizar la solicitud de reservas, realizar la solicitud de contratación de algún producto, la prestación y administración de los servicios de Oca Hotels a través de www.ocahotels.com, la suscripción a boletines informativos, la remisión de publicidad y otras promociones comerciales mediante correo electrónico o correo ordinario, sí es necesario que el USUARIO aporte datos en los formularios existentes en el sitio web para las finalidades anteriormente descritas.</p>

                <p>Todos los campos son obligatorios salvo aquellos que se señalen específicamente como opcionales.</p>

                <p>De no cubrirse alguno de los campos marcados como obligatorios la consecuencia sería la imposibilidad de confirmar la reserva o contratación de servicios, derivándose en ese caso en la imposibilidad de realizar la reserva o contratación a través del portal de Oca Hotels.</p>

                <p>El USUARIO y/o CLIENTE declarara que todos los datos aportados en el momento del registro son ciertos y veraces, a la vez que se compromete a la comunicación de cualquier cambio que en el futuro se produzca sobre los mismos que puedan afectar a las relaciones comerciales presentes y futuras que pueda mantener con Inv. Hosteleras de Galicia S.L.</p>

                <p>Oca Hotels como responsable del fichero, se compromete a respetar la confidencialidad de su información de carácter personal y a garantizar el nivel de seguridad adecuado al tipo de datos y tratamientos efectuados.</p>

                <p>Igualmente se compromete a no ceder sus datos personales a terceras empresas, salvo en los casos en los que resulte estrictamente necesario para poder dar un correcto cumplimiento a las finalidades indicadas anteriormente.</p>

                <p>Oca Hotels informa al USUARIO que mediante la adhesión a las presentes condiciones generales presta su consentimiento a la comunicación necesaria e imprescindible de sus datos para gestionar los servicios que tiene contratados, comunicación ligada con la finalidad misma por la que los datos fueron introducidos y, por tanto, relacionada con la libre y legítima aceptación de la relación jurídica entre el USUARIO y Oca Hotels, cuyo desarrollo, cumplimiento y control implica la comunicación necesaria de estos datos.</p>

                <p>No obstante en cualquier momento puede revocar su consentimiento para cualquiera de las finalidades indicadas, además de ejercitar los derechos de acceso, rectificación, cancelación y oposición de acuerdo con la Ley. Para ejercitar estos derechos deberá dirigirse a "Oca Hotels", Miguel Ferro Caaveiro S/N. Oficina 1019 - 15707. Santiago de Compostela (A Coruña) o la dirección de correo electrónico lopd@ocahotels.es acompañando copia de su D.N.I.</p>

            </div>
        </div>
    </div>
    
</section>