<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/allariz/entorno/003-entorno.jpeg')"></div>
                   </div>
               </div>
         

    <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/san-vicente/entorno/009-entorno-san-vicente.jpg')"></div>
                   </div>
               </div>
            
                <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/apartamentos-seaview-viveiro/entorno/002-entorno-seaview-viveiro.jpg')"></div>
                   </div>
               </div>


            
            <div class="carousel-caption">
                <h1 class="text-uppercase ">Hoteles de turismo rural</h1>
                <h2 style="font-size:1.3em !important; font-weight: 300;">Vacaciones con encanto en entorno rural con OCA Hotels.</h2>
              
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="breadcrumb pd-l-0"><a href="/">OCA HOTELS</a> > <a href="/experiencias">EXPERIENCIAS</a> > TURISMO RURAL</div>
           <div class="ol-xs-12 col-xs-push-0  col-md-12 col-lg-5">
              
               <h3 style="line-height: inherit">Hoteles y apartamientos vacacionales para turismo rural en Sanxenxo, O Grove, Vigo, Allariz, Oviedo...</h3>
               
                 <h4 style="line-height: inherit;">
</h4>
                
               <p></p>
                    <br>
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-lg-6 col-lg-push-1"> 
  
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/santo-domingo-plaza/santo-domingo-plaza-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/asturias/oviedo/oca-santo-domingo-plaza/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Santo Domingo Plaza</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>       
                                                        <i class="fa icon-estrella"></i>     
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Oviedo</h5>
                         <a href="/destinos/asturias/"><h5 class="color-blanco font-light txt-100 mg-t-0">Asturias</h5></a>
                                           </div>
                 </div>
                            </div>
             
                
               
                
                  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/sea-view-viveiro/sea-view-viveiro-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/lugo/viveiro/oca-apartamentos-seaview-viveiro/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Sea View Viveiro</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                                                                        
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Viveiro</h5>
                        <a href="/destinos/lugo/"><h5 class="color-blanco font-light txt-100 mg-t-0">Lugo</h5></a>
                                           </div>
                 </div>
                            </div>
                
                
                
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/ipanema/ipanema-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/pontevedra/vigo/oca-ipanema/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Ipanema</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Vigo</h5>
                        <a href="/destinos/pontebedra/"><h5 class="color-blanco font-light txt-100 mg-t-0">Pontevedra</h5></a>
                                           </div>
                 </div>
                            </div>
                
                
                
            
                
                                 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/vermar/vermar-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/pontevedra/sanxenxo/oca-vermar/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Vermar</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                          <i class="fa icon-estrella"></i> 
                                                            <i class="fa icon-estrella"></i> 
                                                                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Sanxenxo</h5>
                        <a href="/destinos/pontebedra/"><h5 class="color-blanco font-light txt-100 mg-t-0">Pontevedra</h5></a>
                                           </div>
                 </div>
                            </div>
                
                         
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/portonovo-pico/portonovo-pico-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/pontevedra/sanxenxo/oca-portonovo-pico/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Portonovo Pico</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                                                                        
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Sanxenxo</h5>
                        <a href="/destinos/pontebedra/"><h5 class="color-blanco font-light txt-100 mg-t-0">Pontevedra</h5></a>
                                           </div>
                 </div>
                            </div>
                
                
            
                
                
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/san-vicente/san-vicente-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/pontevedra/o-grove/oca-san-vicente/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">San Vicente</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                         <i class="fa icon-estrella"></i> 
                                                                                                        
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">O Grove</h5>
                        <a href="/destinos/pontebedra/"><h5 class="color-blanco font-light txt-100 mg-t-0">Pontevedra</h5></a>
                                           </div>
                 </div>
                            </div>
                
               
                
          
                
                
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">

                        <a href="/hoteles/espana/ourense/allariz/oca-allariz/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 16px !important; text-shadow: 2px 1px 1px black;">Vila de Allariz</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Allariz</h5>
                         <a href="/destinos/ourense/"><h5 class="color-blanco font-light txt-100 mg-t-0">Ourense</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
                
        

                
                
        
                       

                
              
                
                
                     
                     
                       
                        
    
             

               </div>
          
           
    </div>
    </div>
</section>



<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



