<?php 

   
    $fecha=date('Y-m-d');


?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Prevision Forfaits")?></h3>
                <table style="width:100%; background: #FFF;" cellpadding="0" cellspacing="0" border="0">
   <tr>
        <td style="padding:30px 0px">
            <table style="width:90%;" align="center" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td style="width:100%;text-align:center;background-color:#b4b4b9 ;padding:30px 20px;box-shadow: 1px 1px 14px #ddd;" valign="center" align="center">
                        <img src="http://www.ocahotels.com/images/logo-oca-manzaneda.png" width="115px" alt="Oca Hotels">
                        <h2 style="color:#FFF;font-size:2.4em;font-weignt:300;margin-top:10px;margin-bottom:5px;padding:0 0">Manzaneda</h2>
                        <h3 style="color:#FFF;font-size:1,8em;font-weignt:300;margin-top:5px;margin-bottom:5px;padding:0 0">Estación de Montaña</h2>
                    </td>
                </tr>
            </table>
            <table style="background:#f3f3f3;width:90%;" align="center" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td style="padding:50px 30px">
                        
                        <div style=" display:block;width:100%;">
                            <h4 style="text-align:center">Venta de Forfait Online: <?=$fecha?></h4>
                            
                         

        
                        </div>
              
                    </td>
                </tr>
                
            </table>
           
             <table style="background: #FFF;" align="center" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td style="width:100%;padding:20px 12px;height:30px;font-size:0.96em" valign="center" align="left">
        
                        <div style="display:block;width:100%;text-align:center;padding-top:4%;">
                             info@ocahotels.com
                        </div>
                        <div style="display:block;width:100%;text-align:center;padding-top:4%;">
                             Copyright © Oca Hotels, 2018 
                        </div>
                     
                    </td>
                 
                </tr>
            </table>
        </td>
   </tr>
</table>
               
                
                
                
        </div>
    </div>
    
</section>