<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/puerta-del-camino/bodas/002-eventos-puerta-del-camino.jpg')"></div>
                   </div>
               </div>
         

    <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/augas-santas/eventos/0001-eventos.jpg')"></div>
                   </div>
               </div>
            
            <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/allariz/eventos/0002-eventos.jpeg')"></div>
                   </div>
               </div>


            
            <div class="carousel-caption">
                <h1 class="text-uppercase ">Hoteles para bodas, celebraciones  y eventos</h1>
                <h2 style="font-size:1.3em !important; font-weight: 300;">Celebre la boda de sus sueños con Oca Hotels en alguno de nuestros fantásticos hoteles</h2>
              
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="breadcrumb pd-l-0"><a href="/">OCA HOTELS</a> > <a href="/experiencias">EXPERIENCIAS</a> > BODAS Y CELEBRACIONES</div>
           <div class="ol-xs-12 col-xs-push-0  col-md-12 col-lg-5">
              
               <h3 style="line-height: inherit">Hoteles OCA adaptados para eventos y celebraciones de todo tipo.</h3>
               
                 <h4 style="line-height: inherit;">Cada uno de estos enclaves cuenta con instalaciones perfectas para la celebración de bodas y banquetes de gran número de asistentes, así como un equipo humano de amplia experiencia que se encargará de que ese día tan especial salga a pedir de boca.
</h4>
                
               <p>Le invitamos a visitar previamente nuestras instalaciones para que conozca el lugar y al equipo de profesionales que le asesorará durante su estancia.</p><p>

                   Pregunte por nuestros menús para la ocasión o configure un menú a su medida, incluyendo los menús especiales para personas con algún tipo de alergia o intolerancia alimentaria.</p><p>

Lo tenemos todo para hacer de ese día tan señalado una experiencia inolvidable que quedará para siempre en la memoria de sus invitados:</p>
               <ul><li>Decoración floral <li>Música</li> <li>Degustación de menús</li><li>Suite nupcial</li><li>Precios especiales para los invitados</li><li>Transporte</li><li>Barra libre</li><li>Discoteca</li><li>Guardería</li><li>Animación infantil</li>
<li>Y mucho más!</li></ul>
                    <br>
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-lg-6 col-lg-push-1"> 
  
        
           <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/puerta-del-camino/puerta-del-camino-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-puerta-del-camino/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Puerta del Camino</h3></a>
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                        <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>       
                        <a href="/destinos/a-coruna/"><h5 class="color-blanco font-light txt-100 mg-t-0">A Coruña</h5></a>
                    </div> 
                </div>                
            </div>
                
     
                
                
                
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/santo-domingo-plaza/santo-domingo-plaza-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/asturias/oviedo/oca-santo-domingo-plaza/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Santo Domingo Plaza</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>       
                                                        <i class="fa icon-estrella"></i>     
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Oviedo</h5>
                         <a href="/destinos/asturias/"><h5 class="color-blanco font-light txt-100 mg-t-0">Asturias</h5></a>
                                           </div>
                 </div>
                            </div>
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">

                        <a href="/hoteles/espana/asturias/gijon/oca-palacio-llorea/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Palacio de la Llorea</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Gijón</h5>
                             <a href="/destinos/asturias/"><h5 class="color-blanco font-light txt-100 mg-t-0">Asturias</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
                
               
                
                
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/augas-santas/augas-santas-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">

                        <a href="/hoteles/espana/lugo/panton/oca-augas-santas/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Augas Santas</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Pantón</h5>
                              <a href="/destinos/lugo/"><h5 class="color-blanco font-light txt-100 mg-t-0">Lugo</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
                  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/aldeaduero/aldeaduero-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">

                        <a href="/hoteles/espana/castilla-y-leon/salamanca/oca-hotel-oca-aldeaduero/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 1px 1px black;">Aldeaduero</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Salamanca</h5>
                        <a href="/destinos/castilla-leon/"><h5 class="color-blanco font-light txt-100 mg-t-0">Castilla y León</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                               
                 
              
                
             
                
               
                
                  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">

                        <a href="/hoteles/espana/ourense/allariz/oca-allariz/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 16px !important; text-shadow: 2px 1px 1px black;">Vila de Allariz</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Allariz</h5>
                         <a href="/destinos/ourense/"><h5 class="color-blanco font-light txt-100 mg-t-0">Ourense</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
                
        
                       

                
              
                
                
                     
                     
                       
                        
    
             

               </div>
          
           
    </div>
    </div>
</section>



<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



