<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles-camino-de-santiago/hoteles-camino-de-santiago-home.jpg')"></div>
                   </div>
               </div>
         

    <div class="item ">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles/insua/camino-de-santiago/0001-oca-insua-camino-de-santiago.jpg')"></div>
                   </div>
               </div>


            
            <div class="carousel-caption">
                <h1 class="text-uppercase ">Hoteles en el Camino de Santiago</h1>
                <h2 style="font-size:1.3em !important; font-weight: 300;">Encuentre alojamiento confortable para hacer el Camino de Santiago en su paso por Galicia y Asturias</h2>
              
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="breadcrumb pd-l-0"><a href="/">OCA HOTELS</a> > <a href="/experiencias">EXPERIENCIAS</a> > CAMINO DE SANTIAGO</div>
           <div class="ol-xs-12 col-xs-push-0  col-md-12 col-lg-5">
              
               <h3 style="line-height: inherit">Haz el Camino de Santiago más confortable pasando la noche en uno de nuestros hoteles.</h3>
               
                 <h4 style="line-height: inherit;">
Gracias a nuestro programa OCA EN EL CAMINO, los peregrinos del Camino de Santiago gozan de las siguientes ventajas extra durante su ruta a través de Galicia.</h4>
                
               <p>Servicio de lavandería con tarifa especial</p><p>
                   Preparación de bolsa de picnic</p><p>
                   Libro de información para peregrinos</p><p>
                   Servicio de masajistas, bajo demanda</p><p>
                   OCA BIKE SERVICE: zona para guardar las bicicletas con espacio para su limpieza y mantenimiento. Servicio de transporte de bicicletas bajo demanda</p><p>
                   Menú especial para peregrinos, en el propio hotel o en restaurante próximo</p><p>
Servicio de traslado de mochilas personas</p>
                    <br>
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-lg-6 col-lg-push-1"> 
  
        
           <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/puerta-del-camino/puerta-del-camino-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-puerta-del-camino/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Puerta del Camino</h3></a>
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                        <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>       
                        <a href="/destinos/a-coruna/"><h5 class="color-blanco font-light txt-100 mg-t-0">A Coruña</h5></a>
                    </div> 
                </div>                
            </div>
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/insua-costa-da-morte/insua-costa-da-morte-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/a-coruna/cee/oca-insua/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Insua Costa da Morte</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Cee</h5>
                        <a href="/destinos/a-coruna/"><h5 class="color-blanco font-light txt-100 mg-t-0">A Coruña</h5></a>
                                           </div>
                 </div>
                            </div>
                
                
                         <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/cruceiro-do-galo/cruceiro-do-galo-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height:170px;">
                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-apartamentos-cruceiro-do-galo/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Cruceiro do Galo</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>
                         <a href="/destinos/a-coruna/"><h5 class="color-blanco font-light txt-100 mg-t-0">A Coruña</h5></a>
                                           </div>
                 </div>
                            </div>
                
                           <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/sete-artes/sete-artes-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-sete-artes/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Sete Artes</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                         <i class="fa icon-estrella"></i>                                                                                                         
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>
                         <a href="/destinos/a-coruna/"><h5 class="color-blanco font-light txt-100 mg-t-0">A Coruña</h5></a>
                                           </div>
                 </div>
                            </div>

                
                  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/casa-reales/casa-reales-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-casas-reales/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Casa Reales</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-llave"></i> 
                                                                                                        
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Santiago de Compostela</h5>
                         <a href="/destinos/a-coruna/"><h5 class="color-blanco font-light txt-100 mg-t-0">A Coruña</h5></a>
                                           </div>
                 </div>
                            </div>
                
                
                
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/santo-domingo-plaza/santo-domingo-plaza-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/asturias/oviedo/oca-santo-domingo-plaza/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Santo Domingo Plaza</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>       
                                                        <i class="fa icon-estrella"></i>     
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Oviedo</h5>
                         <a href="/destinos/asturias/"><h5 class="color-blanco font-light txt-100 mg-t-0">Asturias</h5></a>
                                           </div>
                 </div>
                            </div>
                
                
                
                               
                 
              
                
                 <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/rio-pambre/rio-pambre-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/lugo/palas-de-reis/oca-rio-pambre/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Río Pambre</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i>                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Palas de Reis</h5>
                         <a href="/destinos/lugo/"><h5 class="color-blanco font-light txt-100 mg-t-0">Lugo</h5></a>
                                           </div>
                 </div>
                            </div>
                
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 pd-l-2 pd-r-2">              
                <div class="text-center back-image5 hotel-duerming" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/vila-de-sarria/vila-de-sarria-home.jpg'); background-size: cover;">
                                      <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">
                        <a href="/hoteles/espana/lugo/sarria/oca-villa-de-sarria/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 6px !important; text-shadow: 2px 1px 1px black;">Vila de Sarria</h3></a>
                         <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                          <i class="fa icon-estrella"></i> 
                                                                                                      
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Sarria</h5>
                           <a href="/destinos/lugo/"><h5 class="color-blanco font-light txt-100 mg-t-0">Lugo</h5></a>
                                           </div>
                 </div>
                            </div>
                
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 pd-l-2 pd-r-2">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 170px;background-image: url('/images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg'); background-size: cover;">
                  
                    <div class="ps-rel wd-100 text-center" style="top:0;background:rgba(0,0,0,0.2);min-height: 170px;height: 170px;">

                        <a href="/hoteles/espana/ourense/allariz/oca-allariz/"><h3 style="color: #FFF; font-weight: 300; margin-bottom: 16px !important; text-shadow: 2px 1px 1px black;">Vila de Allariz</h3></a>
 
                        <div class="txt-90 mg-b-1 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                        </div>
                       <h5 class="color-blanco font-light txt-100 mg-t-0">Allariz</h5>
                         <a href="/destinos/ourense/"><h5 class="color-blanco font-light txt-100 mg-t-0">Ourense</h5></a>
                       
                    </div>
 
                </div>
                
            </div>
                
                
        
                       

                
              
                
                
                     
                     
                       
                        
    
             

               </div>
          
           
    </div>
    </div>
</section>



<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



