<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo _("Atención al cliente")?></h3>
                
                <p>¿Tiene algún tipo de duda sobre nuestro servicio o quiere hacernos un comentario sobre su estancia en nuestros hoteles? Por favor, rellene el siguiente formulario y nuestro equipo de atención al cliente se pondrá en contacto con usted:</p>
                
                
                  <div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
               <!-- BEGIN Podio web form -->
<script src="https://podio.com/webforms/19128042/1287564.js"></script>
<script type="text/javascript">
  _podioWebForm.render("1287564")
</script>
<noscript>
  <a href="https://podio.com/webforms/19128042/1287564" target="_blank">Por favor, rellena el formulario</a>
</noscript>

<!-- END Podio web form -->




            </div>
        </div>
    </div>
    
</section>