<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs1-2">
                <h3>PERSONAL DATA PROTECTION. PRIVACY POLICY</h3>
                
                <p>Oca Hotels, Oca Termal Hotels and Grand Oca Hotels & Resort are registered trademarks of Inversiones Hosteleras de Galicia S.L. (I.H.G.) with tax code CIF: B36348217 and business address Miguel Ferro Caaveiro S/N. Office 1019, Postcode 15707, Santiago de Compostela (A Coruña). Company registered in the Commercial Registry of Pontevedra (Volume 2416, Book 2416, Folio 68, Page PO-24980).</p>
                
                <p>Oca Hotels informs you that according to the article 5 on the Law 15/1999 on the 13th of December on the Protection of Personal Data, all data that USERS facilitate while filling up their registration on the Web, will be added to the folders owned by Oca Hotels in order to manage reservations, as well as to manage subscription to the Golf Course of Oca Augassantas Hotel & Spa; USERS have the possibility to consent the sending of commercial communications related to the product currently offered or that may be offered in the future by Oca Hotels through the Web. In order to access the Web no data is needed.</p>

               

                <p>However, in order to apply for a booking, to hire a product, provision and administration of services by Oca Hotels through www.ocahotels.com, subscription to newsletters, sending of advertising and other commercial promotions by mail or e-mail, it is mandatory that USERS provide all data needed in order to fill applications located on the web for the purposes previously described.</p>

                <p>All fields are required to be filled in except those specifically identified as optionals.
If any mandatory field is not filled in, the consequence would be the impossibility to confirm the booking or the hiring of services, being thus impossible to make the reservation or hiring through Oca Hotels’ Web.</p>

                <p>USERS and/or CLIENTS declare that all data provided while registering are true and accurate, at the same time that they pledge to communicate any change about them that may occur in the future and which may affect present and future business relations with Inv. Hosteleras de Galicia S.L.</p>

                <p>Oca Hotels, as responsible of the files, pledges to respect the confidentiality of the personal information data and guarantee the level of security adequate to the type of data and processing carried out.</p>

                <p>Oca Hotels also pledges not to hand out their personal data to third parties, except in the cases when it is strictly necessary for the proper execution of the purposes aforementioned.</p>

                <p>Oca Hotels informs USERS that by agreeing to this General Conditions they consent to the necessary and essential communication of their data in order to manage hired services, communication linked to the same purpose said data was firstly filled in and, therefore, related to the free and legitimate acceptance of the legal relation between USERS and Oca Hotels, whose development, fulfillment and control implies the necessary communication of said data.</p>

                <p>However, users can, at any time, revoke their consent to any of the purposes before mentioned, as well as execute their rights of access, rectification, cancellation and opposition according to the Law. In order to execute these rights they must address to  "Oca Hotels", Miguel Ferro Caaveiro S/N. Office 1019. Postcode 15707. Santiago de Compostela (A Coruña) or by e-mail to lopd@ocahotels.es along with a copy of their ID.</p>

            </div>
        </div>
    </div>
    
</section>