<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs1-2">
               <p align="center"><strong>POLITICA DE PRIVACIDAD (I)</strong></p>
<p align="justify"><br/>
  <br/>
</p>
<p align="justify"><strong>1</strong><strong>. DATOS IDENTIFICATIVOS: </strong>En cumplimiento del deber de información recogido en el artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y del Comercio electrónico, a continuación se reflejan los siguientes datos: la empresa titular de <u><a href="file:///C:%5CUsers%5CAYS%20innova%201%5CDropbox%5CAYS%20LOPD%5CPLANTILLAS%5CDocumento%20Completo%20RGPD%5CCL%C3%81USULAS%20RGPD%5CWeb%5Cwww.XXXXX.com">www.ocahotels.com </a></u> es <strong> </strong><strong>INVERSIONES HOSTELERAS DE GALICIA, S.L.</strong><strong>, </strong>con CIF B36348217 y domicilio a estos efectos en C/ Miguel Ferro Caaveiro, s/n, 15.703, Santiago de Compostela (A Coruña) con correo electrónico de contacto: <a href="mailto:lopd@grupomascostas.com"><u>lopd@ocahotels.es</u></a></p>
<p align="justify"><br/>
</p>
<p align="justify"><strong>2. USUARIOS: </strong>El acceso y/o uso de este portal de <strong>INVERSIONES HOSTELERAS DE GALICIA, S.L. </strong>atribuye la condición de USUARIO, que acepta, desde dicho acceso y/o uso, las Condiciones Generales de uso aquí reflejadas. Las citadas condiciones serán de aplicación independientemente de las Condiciones Generales de Contratación que en su caso resulten de obligado cumplimiento.</p>
<p align="justify"><br/>
</p>
<p align="justify"><strong>3. USO DEL PORTAL: </strong><u><a href="file:///C:%5CUsers%5CAYS%20innova%201%5CDropbox%5CAYS%20LOPD%5CPLANTILLAS%5CDocumento%20Completo%20RGPD%5CCL%C3%81USULAS%20RGPD%5CWeb%5Cwww.XXXXX.com">www.ocahotels.com </a></u> proporciona el acceso a multitud de informaciones, servicios, programas o datos (en adelante, &ldquo;los contenidos&rdquo;) en Internet pertenecientes a <strong>INVERSIONES HOSTELERAS DE GALICIA, S.L. </strong>a los que el USUARIO pueda tener acceso. EL USUARIO asume la responsabilidad de uso del portal. Dicha responsabilidad se extiende al registro que fuese necesario para acceder a determinados servicios o contenidos.</p>
<p align="justify">En dicho registro el USUARIO será responsable de aportar información veraz y lícita. Como consecuencia de este registro, al USUARIO se le puede proporcionar una contraseña de la que será responsable, comprometiéndose a hacer un uso diligente y confidencial de la misma. EL USUARIO  se compromete a hacer un uso adecuado de los contenidos y servicios que <strong>INVERSIONES HOSTELERAS DE GALICIA, S.L. </strong>ofrece a través de su página Web, comprometiéndose a no utilizarlos para actividades que puedan ser ilícitas, contrarias al orden público, a la defensa nacional o a la salud pública.</p>
<p align="justify"><br/>
</p>
<p align="justify">En todo caso, <strong>INVERSIONES HOSTELERAS DE GALICIA, S.L. </strong>se reserva el derecho de modificar unilateralmente, en cualquier momento y sin necesidad de previo aviso, la estructura y diseño del sitio Web: modificar o eliminar servicios o contenidos así como las condiciones de acceso y/o uso del sitio Web.</p>
<p align="justify"><br/>
</p>
<p align="justify">Del mismo modo <strong>INVERSIONES HOSTELERAS DE GALICIA, S.L. </strong>se reserva el derecho a modificar en cualquier momento las presentes condiciones de uso, así como cualesquiera otras condiciones particulares contenidas en el sitio web <u><a href="file:///C:%5CUsers%5CAYS%20innova%201%5CDropbox%5CAYS%20LOPD%5CPLANTILLAS%5CDocumento%20Completo%20RGPD%5CCL%C3%81USULAS%20RGPD%5CWeb%5Cwww.XXXXX.com">www.ocahotels.com </a></u></p>
<p><br/>
</p>
<p align="justify"> <strong>4. PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL</strong></p>
<table width="660" cellpadding="8" cellspacing="0" border="1">
  <col width="130">
  <col width="496">
  <tr>
    <td colspan="2" width="642" height="10" ><p  align="center"><strong>INFORMACIÓN 			BÁSICA SOBRE PROTECCIÓN DE DATOS</strong></p></td>
  </tr>
  <tr>
    <td width="130">
     
      <p ><strong>Responsable</strong></p></td>
    <td width="496" valign="top">
    
      <p  align="justify"> INVERSIONES 			HOSTELERAS DE GALICIA, S.L.</p></td>
  </tr>
  <tr>
    <td width="130">
      <p ><strong>Finalidad</strong></p></td>
    <td width="496" valign="top">
      <p  align="justify">Gestión 			de la solicitud</p></td>
  </tr>
  <tr>
    <td width="130"><p > <br/>
    </p>
      <p ><strong>Legitimación</strong></p></td>
    <td width="496" valign="top"><p  align="justify"> Ejecución 			de un contrato / prestación de servicios</p></td>
  </tr>
  <tr>
    <td width="130"><p > <br/>
    </p>
      <p ><strong>Destinatarios</strong></p></td>
    <td width="496" valign="top"><p  align="justify"> <br/>
    </p>
      <p  align="justify">Otras 			empresas o filiales del  grupo</p></td>
  </tr>
  <tr>
    <td width="130"><p > <br/>
    </p>
      <p ><strong>Derechos</strong></p></td>
    <td width="496" valign="top"><p  align="justify"> <br/>
    </p>
      <p  align="justify">Puede 			ejercitar  los Acceso, rectificación, supresión, limitación, 			oposición y portabilidad 			de los datos aportados, como se indica en la información 			adicional.</p></td>
  </tr>
  <tr>
    <td width="130"><p > <br/>
    </p>
      <p ><strong>Información 			Adicional</strong></p></td>
    <td width="496" valign="top"><p > <br/>
    </p>
      <p > Puede consultar la información 			adicional y detallada sobre Protección de Datos siguiendo el 			siguiente enlace </p>
      <p  align="center"><strong>+Info 			Protección de Datos</strong></p></td>
  </tr>
</table>
<p align="justify"><br/>
</p>
<p align="center"><strong>POLITICA DE PRIVACIDAD (II) </strong></p>
<p align="center"><strong>+Info Protección de Datos</strong></p>
<p align="justify"> <br/>
</p>
<p align="justify"> <br/>
</p>
<table width="660" cellpadding="8" cellspacing="0" border="1">
  <col width="129">
  <col width="497">
  <tr>
    <td colspan="2" width="642" height="10" ><p  align="center"><strong>INFORMACIÓN 			DETALLADA PROTECCIÓN DE DATOS</strong></p></td>
  </tr>
  <tr>
    <td width="129"><p > <br/>
    </p>
      <p > <br/>
      </p>
      <p ><strong>Responsable</strong></p></td>
    <td width="497" valign="top"><p  align="justify"> <br/>
    </p>
      <p  align="justify"> <br/>
      </p>
      <p  align="justify"> <em><strong>¿Quién 			es el Responsable del tratamiento de sus datos?</strong></em></p>
      <p  align="justify"> Identidad: 			INVERSIONES HOSTELERAS DE GALICIA, S.L.</p>
      <p  align="justify"> Domicilio 			Social: 			 			 			C/ Miguel Ferro Caaveiro, s/n, 15.703, Santiago de Compostela (A 			Coruña)</p>
      <p  align="justify"> Teléfono: 			 981107005</p>
      <p align="justify"><span >Email: </span><a href="mailto:lopd@grupomascostas.com"><span ><u>lopd@ocahotels.es</u></span></a></p>
      <p  align="justify">Contacto 			DPD: </p></td>
  </tr>
  <tr>
    <td width="129"><p > <br/>
    </p>
      <p ><strong>Finalidad</strong></p></td>
    <td width="497" valign="top"><p  align="justify"> <br/>
    </p>
      <p  align="justify"> <em><strong>¿Con 			qué finalidad tratamos sus datos personales?</strong></em></p>
      <p  align="justify"> En 			INVERSIONES HOSTELERAS DE GALICIA, S.L. tratamos la información 			que nos facilitan las personas interesadas con el fin de gestionar 			el envió de la información o de los productos solicitados.</p>
      <p  align="justify"> Se 			realizarán tratamientos de datos automatizados con el fin de 			elaborar perfiles con los servicios solicitados o compras 			realizadas, para poder ofrecerle promociones, ofertas o servicios 			por los que ha mostrado interés.</p>
      <p  align="justify"> <em><strong>¿Por 			cuánto tiempo conservaremos sus datos?</strong></em></p>
      <p  align="justify"> Los 			datos personales facilitados por el usuario se conservarán 			mientras no se solicite la supresión de los mismos por parte del 			interesado.</p>
      <p  align="justify"><br/>
      </p></td>
  </tr>
  <tr>
    <td width="129"><p > <br/>
    </p>
      <p ><strong>Legitimación</strong></p></td>
    <td width="497" valign="top"><p  align="justify"> <br/>
    </p>
      <p  align="justify">La 			base legal para el tratamiento de sus datos es la ejecución de su 			solicitud.</p></td>
  </tr>
  <tr>
    <td width="129"><p > <br/>
    </p>
      <p ><strong>Destinatarios</strong></p></td>
    <td width="497" valign="top"><p  align="justify"> <br/>
    </p>
      <p  align="justify"> <em><strong>¿A 			qué destinatarios se comunicarán sus datos?</strong></em></p>
      <p  align="justify"><a name="_GoBack"></a> INVERSIONES HOSTELERAS DE 			GALICIA, S.L. podrá ceder sus datos a otras empresas o filiales 			del grupo Oca Hotels para fines administrativos y de gestión 			interna.</p></td>
  </tr>
  <tr>
    <td width="129"><p > <br/>
    </p>
      <p ><strong>Derechos</strong></p></td>
    <td width="497" valign="top"><p  align="justify"> <br/>
    </p>
      <p align="justify"><span >El 			usuario podrá ejercer en todo momento los derechos de Acceso, 			Rectificación, Supresión, Limitación, Oposición y Portabilidad</span><span > de los datos aportados,  según lo dispuesto en el </span><span >Reglamento 			General (UE) 2016/679 de Protección de Datos, dirigiendo un 			escrito en que especifique que derecho desea ejercer al domicilio 			social arriba indicado, adjuntando copia del documento que lo 			identifique, a la dirección de correo electrónico </span><a href="mailto:lopd@grupomascostas.com"><span ><u>lopd@ocahotels.es</u></span></a></p>
      <p  align="justify"> Asimismo, el interesado 			puede presentar una reclamación ante la Autoridad de Control.</p>
      <p  align="justify"><br/>
      </p></td>
  </tr>
</table>
<p align="justify"> <br/>
</p>
<p align="justify"><br/>
</p>
<p align="justify">En cumplimiento de lo establecido en el Reglamento General (UE) 2016/679 de Protección de Datos, comunicamos al usuario que los datos personales que nos facilite de forma voluntaria , por cualquiera de nuestros medios de recogida de información, van a ser incorporados a las Actividades de Tratamiento automatizados de datos de carácter personal titularidad de <strong>INVERSIONES HOSTELERAS DE GALICIA, S.L.</strong>, con el fin de poderle prestar nuestros servicios, así como para mantenerle informado sobre cuestiones relativas a la actividad de la empresa y sus servicios. Los campos marcados con &ldquo;*&rdquo; son de carácter obligatorio, por lo que la no cumplimentación de dichos campos impedirá al USUARIO  disfrutar de algunos de los Servicios e informaciones ofrecidas en la Web. Los datos contenidos en ellos serán tratados de forma confidencial. </p>
<p align="justify"><br/>
</p>
<p align="justify"><strong>INVERSIONES HOSTELERAS DE GALICIA, S.L.</strong> cumple íntegramente con la legislación vigente en materia de protección de datos de carácter personal, y con los compromisos de confidencialidad propios de su actividad.</p>
<p align="justify"><br/>
</p>
<p align="justify"><strong>INVERSIONES HOSTELERAS DE GALICIA, S.L. </strong>ha adoptado las medidas técnicas necesarias para mantener el nivel de seguridad requerido, según la naturaleza de los datos personales tratados y las circunstancias del tratamiento, con el objeto de evitar, en la medida de lo posible y siempre según el estado de la técnica, su alteración, pérdida, tratamiento o acceso no autorizado. Para la realización de la gestión antes mencionada puede ser necesario que se cedan los datos a encargados del tratamiento, empresas colaboradoras y administraciones públicas (las cuales pueden verificar la veracidad de los datos).</p>
<p align="justify"><br/>
</p>
<p align="justify">En caso de que el USUARIO  facilite datos de carácter personal, referentes a personas físicas distintas a sí mismo, el USUARIO deberá, con carácter previo a la inclusión, informarles del contenido de la presente clausula, de acuerdo con lo  establecido en el Reglamento General (UE) 2016/679 de Protección de Datos.</p>
<p align="justify"><br/>
</p>
<p align="justify"><strong>INVERSIONES HOSTELERAS DE GALICIA, S.L. </strong>como responsable de la Actividad de Tratamiento, garantiza el ejercicio de los derechos de acceso, rectificación, supresión, limitación, oposición y portabilidad de los datos aportados, según lo dispuesto en el Reglamento General (UE) 2016/679 de Protección de Datos, el USUARIO podrá ejercer en todo momento los derechos, dirigiendo un escrito al domicilio social, adjuntando copia del DNI o Pasaporte.</p>
<p align="justify"><br/>
</p>
<p align="justify"><strong>INVERSIONES HOSTELERAS DE GALICIA, S.L.</strong> garantiza que todas las comunicaciones comerciales que dirige a sus clientes cumplen la normativa vigente.</p>
<p align="justify"><br/>
</p>
<p align="justify">Por ello, en cumplimiento de la Ley 34/2002 de Servicios de la Sociedad de la Información y de Comercio Electrónico y la Ley 9/2014 General de Telecomunicaciones, se informa al USUARIO que <strong>INVERSIONES HOSTELERAS DE GALICIA, S.L. </strong>podrá enviarle por medios electrónicos información acerca de productos y servicios de interés a lo que Ud. presta su consentimiento</p>
<p align="justify"> <br/>
</p>
<p align="justify">En cualquier momento podrá revocar esta autorización en la dirección <a href="mailto:lopd@grupomascostas.com"><u>lopd@ocahotels.es</u></a></p>

            </div>
        </div>
    </div>
    
</section>