<style type="text/css">
    a .manzanedaSpecial {
        text-align: center;
        padding: 15px 10px;
        background-color: #b4b4b9;    
        color: #FFF;
        font-size: 20px;
    }
    a:hover .manzanedaSpecial{
        background-color: #ff690f;
    }
    
       a .manzanedaSpecialForfait {
        text-align: center;
        padding: 15px 10px;
        background-color: #ff690f;    
        color: #FFF;
        font-size: 20px;
    }
    a:hover .manzanedaSpecialForfait{
        background-color: #db5200;
    }
</style><div id="buscador-horizontal" class="container-fluid pd-l-0 pd-r-0">

    
    <a href="http://ocahotels.com/hoteles/espana/ourense/pobra-de-trives/oca-manzaneda/forfait"><div class="col-md-3 col-sm-6 col-xs-12 manzanedaSpecialForfait">FORFAIT &nbsp;<i class="icon-esquiables" aria-hidden="true" style="color: rgb(255, 255, 255);"></i></div></a>
    <a href="http://ocahotels.com/hoteles/espana/ourense/pobra-de-trives/oca-manzaneda/parte-de-nieve"><div class="col-md-3 col-sm-6 col-xs-12  manzanedaSpecial">PARTE DE NIEVE  &nbsp;<i class="icon-clima_8" aria-hidden="true" style="color: rgb(255, 255, 255);"></i></div></a>
    <a href="http://ocahotels.com/hoteles/espana/ourense/pobra-de-trives/oca-manzaneda/webcams"><div class="col-md-3 col-sm-6 col-xs-12 manzanedaSpecial">WEBCAMS  &nbsp;<i class="icon-eye" aria-hidden="true" style="color: rgb(255, 255, 255);"></i></div></a>
    <a href="https://bookings.ocahotels.com/es/step-1?id=q3lPoYvt5bQu3Caz4nNmfQ&arrival=1&nights=1" target="_blank"><div class="col-md-3 col-sm-6 col-xs-12 manzanedaSpecial"> ALOJAMIENTO  &nbsp;<i class="icon-key" aria-hidden="true" style="color: rgb(255, 255, 255);"></i></div></a>
</div>


