<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
          <h4 class="modal-title" id="myModalLabel">Comprobar usuario.</h4>
        </div>
        <div class="modal-body">
            <p class="txt-110 mg-b-30 font-light">El código introducido es específico para esta PROMOCIÓN, introduzca el DNI para comprobar su autenticidad y acceder al DESCUENTO.</p>
            <div class="form-horizontal">
                <div class="form-group row">
                    <label for="dni_colectivo" class="col-md-1 control-label mg-r-20">DNI:</label>
                    <div class="col-md-4">
                        <input type="text" name="dni_colectivo" class="form-control" id="dni_colectivo" placeHolder="11111111X" />
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
          <button id="comprobar_colectivo" type="button" class="btn btn-primary">Comprobar</button>        
        </div>
      </div>
    </div>
</div>