<?php 
    if ($datos['longNameTemp'] == 'Sea View Viveiro'){
        ?><div class="col-xs-12 text-center" style="padding: 60px auto;  background-color: #FFF; text-align: center">
            <img src="http://ocahotels.com/images/hoteles/sea-view-viveiro/axudaGALP_duerminseaviewviveiro.jpg" class="img-responsive" style="margin: 0 auto; display: block;"><br><br></div>
    <?php 
    } else {
        
    
        }?>
<section class="pd-t-20 pd-b-20 bck-color-secundario color-blanco" >
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 text-center">
                <h3 class="mg-t-0 pd-t-0 font-light txt-220">
                    <span class="hidden-xs"><?php echo _("Benefíciate de un descuento del 8% con tu registro")?></span> <i class="hidden-xs icon-check-circle mg-r-20 mg-l-20 txt-120"></i>
                    <a href="<?php echo $ROOT?>liveoca/" class="color-blanco"><span class="text-uppercase mg-r-20 txt-120"><?php echo _("LIVE OCA")?></span> <i class="icon-angle-right txt-110 font-bold" ></i></a>
                </h3>
            </div>
        </div>
    </div>
</section>


