<section class="pd-t-50 pd-b-60 bck-color-secundario" style="border-top: 15px solid #fff;border-bottom: 15px solid #fff ">
    <div class="container" id="content-newsletter">
        <div class="row mg-t-15">

            <div class="col-xs-12 col-md-12 mg-md-b-30 mg-b-20">
              
                <p class="txt-200 font-light mg-b-20 color-blanco text-center lt-s-2 pd-md-l-20 pd-md-r-20">
                     <?php echo _("Subscribase a nuestra")?> <span class="font-bold text-uppercase"><?php echo _("Newsletter")?></span> <?php echo _("[ofertas, promociones, novedades ...]")?> 
                </p>
            </div>

            <div class="col-xs-12 col-md-12 mg-md-b-30" >
                
               <!--form id="newsletter_form" method="post" action="#">
                    
                    <div class="row">
                        
                        <div class="col-xs-12 col-md-10 pd-md-l-15 pd-md-r-15">
                            <input  class="txt-a-c-md" type="email" id="email_newsletter" name="email_newsletter" placeholder="<?php echo _("Introduzca su email")?>" required/>
                        </div>

                        <div class="col-xs-12 col-md-2  pd-md-r-15 pd-md-l-15 mg-md-t-15">
                            <button  type="submit" class="btn  btn-primary"><?php echo _("Enviar")?> </button>
                        </div>
                        
                    </div>
        
                </form-->
                <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{ clear:left; font:14px "Lato",sans-serif; width:100%; background: transparent;}
      #mc_embed_signup input {
    padding-left: 30px !important;
    padding-top: 0px !important;
    padding-bottom: 0px !important;
    font-size: 1.8em !important;
    border: 2px solid #7f7f7f !important;
    font-weight: 300 !important;
    height: 84px !important;
    width: 100% !important;
}
#mc_embed_signup button {
    text-transform: uppercase !important;
    padding-top: 22px !important;
    padding-bottom: 23px !important;
    height: 100% !important;
    font-size: 1.8em !important;
    border: 2px solid #7f7f7f !important;
    border-left: none !important;
    font-weight: 300 !important;
    width: 100% !important;
}
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>

<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:transparent; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://ocahotels.us15.list-manage.com/subscribe/post?u=5e9e0387145cf2beb5e311e34&amp;id=69ecb4402d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<div class="col-xs-12 col-md-10 pd-md-l-15 pd-md-r-15">
<div class="mc-field-group">
	
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div></div>
	
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_5e9e0387145cf2beb5e311e34_69ecb4402d" tabindex="-1" value=""></div>
     <div class="col-xs-12 col-md-2  pd-md-r-15 pd-md-l-15 mg-md-t-15"><input type="submit" value="Suscríbase" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
     <div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email'; /*
 * Translated default messages for the $ validation plugin.
 * Locale: ES
 */
$.extend($.validator.messages, {
  required: "Este campo es obligatorio.",
  remote: "Por favor, rellena este campo.",
  email: "Por favor, escribe una dirección de correo válida",
  url: "Por favor, escribe una URL válida.",
  date: "Por favor, escribe una fecha válida.",
  dateISO: "Por favor, escribe una fecha (ISO) válida.",
  number: "Por favor, escribe un número entero válido.",
  digits: "Por favor, escribe sólo dígitos.",
  creditcard: "Por favor, escribe un número de tarjeta válido.",
  equalTo: "Por favor, escribe el mismo valor de nuevo.",
  accept: "Por favor, escribe un valor con una extensión aceptada.",
  maxlength: $.validator.format("Por favor, no escribas más de {0} caracteres."),
  minlength: $.validator.format("Por favor, no escribas menos de {0} caracteres."),
  rangelength: $.validator.format("Por favor, escribe un valor entre {0} y {1} caracteres."),
  range: $.validator.format("Por favor, escribe un valor entre {0} y {1}."),
  max: $.validator.format("Por favor, escribe un valor menor o igual a {0}."),
  min: $.validator.format("Por favor, escribe un valor mayor o igual a {0}.")
});}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->




<!--End mc_embed_signup-->
            </div>
            <div class="col-xs-12 mg-t-15 text-right txt-a-c-md pd-md-l-20 pd-md-r-20">
                <p class="font-light txt-130 color-blanco"><?php echo _("Enviando su información está aceptando las")?> <a href="<?php echo $ROOT?>politica-de-privacidad/" class="bases-legales"><?php echo _("bases legales")?></a></p>
            </div>

        </div>

    </div>
</section>

<script type="text/javascript">
    
    jQuery(document).ready(function () {
        
        jQuery("#newsletter_form").validate({
            rules: {
               
                email_newsletter: "required"
            },
            messages: {

            },
            
            submitHandler: function(form) {
                
               jQuery("#content-newsletter").hide();
               /* $("#loading").show();*/

               var campos = jQuery(form).serialize();

               var url = "<?php echo $ROOT?>services/ajax.php?" + campos;

               var parametros = {operacion:"registro_newsletter"};

                jQuery.ajax({
                        url: url,
                        type: "post",
                        dataType: 'html',
                        data:parametros,
                        success: function(data) {
                            
                           // $("#loading").hide();
                            var obj = JSON.parse(data);
                            jQuery("#content-newsletter").html(obj.mensaje);
                            jQuery("#content-newsletter").addClass("txt-140");
                         
                            jQuery("#content-newsletter").show();
                           console.log(obj);
                        },
                        error: function(jqXHR,textStatus,errorThrown ) {

                        }
                    }).done(function( data ) {

                });
                
            }
           
        });
       
        
    });
</script>

