<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles-para-bodas/hoteles-para-bodas-home.jpg')"></div>
                   </div>
               </div>
         
            
            <div class="carousel-caption">
                <h2 class="text-uppercase txt-220"><?php echo $titulo?></h2>
                <h3 style="font-weight: 300">Celebre la boda de sus sueños con Oca Hotels</h3>
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
           <div class="ol-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2 text-center">
              
               <h2 class="color-accion" style="line-height: inherit">Celebre la boda de sus sueños con Oca Hotels en alguno de nuestros fantásticos hoteles</h2>
               
                 
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2"> 
                <h4 style="line-height: inherit;">Adaptados para eventos y celebraciones de todo tipo (Oca Augas Santas, Palacio de la Llorea, Puerta del Camino, Vila de Allariz, Santo Domingo y Aldeaduero)</h4>
                
                <p>                   Cada uno de estos enclaves cuenta con <b>instalaciones perfectas</b> para la celebración de <b>bodas y banquetes</b> de gran número de asistentes, así como un equipo humano de amplia experiencia que se encargará de que ese día tan especial salga a pedir de boca. </p>
                <p>
                    Le invitamos a visitar previamente nuestras instalaciones para que conozca el lugar y al equipo de profesionales que le asesorará durante su estancia.</p><p>Pregunte por nuestros <b>menús para la ocasión</b> o configure un menú a su medida, incluyendo los menús especiales  para personas con algún tipo de alergia o intolerancia alimentaria. 
                </p><p>
                    Lo tenemos todo para hacer de ese día tan señalado una <b>experiencia inolvidable</b> que quedará para siempre en la memoria de sus invitados: </p>
            
                <h4 style="line-height:inherit" class="text-center">·Decoración floral ·Música ·Degustación de menús ·Suite nupcial ·Precios especiales para los invitados ·Transporte ·Barra libre ·Discoteca ·Guardería ·Animación infantil<br>Y mucho más!</h4>
            <br>
                    <a href="https://podio.com/webforms/19688648/1334904?fields[en-que-esta-interesad]=4" target="_blank" class="pdflink"><h4>SOLICITAR INFORMACIÓN</h4></a></div>
           
           
    </div>
    </div>
</section>
<div id="contenedor-boxes" style="display: block;"><section class="bck-color-blanco">
    <div class="container-fluid ">
        
        <div class="row boxes-destinos">
        
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/aldeaduero/aldeaduero-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Aldeaduero</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Salamanca, Castilla y León</p>

                        <a href="/hoteles/espana/castilla-y-leon/salamanca/oca-hotel-oca-aldeaduero/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/augas-santas/augas-santas-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Augas Santas</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Pantón, Lugo</p>

                        <a href="/hoteles/espana/lugo/panton/oca-augas-santas/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Palacio de la Llorea</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Gijón, Asturias</p>

                        <a href="/hoteles/espana/asturias/gijon/oca-palacio-llorea/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/puerta-del-camino/puerta-del-camino-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Puerta del camino</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Santiago de Compostela, A Coruña</p>

                        <a href="/hoteles/espana/a-coruna/santiago-de-compostela/oca-puerta-del-camino/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/santo-domingo-plaza/santo-domingo-plaza-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Santo Domingo Plaza</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Oviedo, Asturias</p>

                        <a href="/hoteles/espana/asturias/oviedo/oca-santo-domingo-plaza/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/vila-de-allariz/vila-de-allariz-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Vila de Allariz</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Allariz, Ourense</p>

                        <a href="/hoteles/espana/ourense/allariz/oca-allariz/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        
        </div>
        
    </div>
</section>
</div>
<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



