<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs-12">
                <h3>LIVE OCA</h3>
                
                <p>
                    Gracias a nuestro programa <strong>LIVE OCA</strong>, nuestros clientes pueden beneficiarse de un <strong>descuento especial del 8%</strong> sobre el precio la habitación a través de reserva online.<p><p> Para ello solo tiene que completar el cuestionario que encontrará a continuación:
                </p>
                  <div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
                <!-- BEGIN Podio web form -->
<script src="https://podio.com/webforms/18601349/1251789.js"></script>
<script type="text/javascript">
  _podioWebForm.render("1251789")
</script>
<noscript>
  <a href="https://podio.com/webforms/18601349/1251789" target="_blank">Por favor, rellena el formulario</a>
</noscript>
  <div class="podio-webform-container">
  A webform by <a href="https://podio.com" class="podio-webform-inner" rel="nofollow">Podio</a>
  </div>
<!-- END Podio web form -->
            </div>
        </div>
    </div>
    
</section>
<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



