<?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
            <div class="col-xs1-2">
                <h3><?php echo _("Política de Cookies")?></h3>
 


<p align="justify">According to the Spanish regulations that controls the use of cookies in relation to providing information society services, collected on the second section of the article 22 of the Law 34/2002 on the 11th of July, of society information services and electronic commerce, after its modification by Royal Decree Law 13/2012 on the 30th of March, we inform you about the cookies used in the web <a href="http://www.ocahotelscom/"><u>www.ocahotels.com</u></a> and the reason of their use. We also inform you that according to the law (i) USERS consent to the possibility of using them if they modify the configuration of their browser disabling the restrictions that prevent cookies and (ii) that the above-mentioned consent will not be needed to install those cookies that are strictly necessary in order to provide a service expressly demanded by the USER.</p>
<p align="justify"> &nbsp;<strong>- WHAT ARE COOKIES?</strong></p>
<p align="justify">Cookies are small text files installed on the browser of the USER&rsquo;S computer to register their activity sending an anonymous identification that is stored in itself. The objective is to make web browsing easier, allowing for example, the access to USERS who have registered before, the access to different sections, services or promotions exclusively reserved to them without having to log in every time they visit the Web. Cookies can also be used to measure audience, traffic and browsing parameters, session duration, and/or control the progress and number of entries. Cookies are associated to only one anonymous user and their computer or device and they do not provide any reference that would allow to know their personal data. </p>
<p align="justify"> <strong>TYPES OF COOKIES:</strong></p>
<p>1.- Own Cookies: those sent to the user&rsquo;s device from a unit or domain managed by the editor and that provides the service requested by the user. </p>
    <p>2.- Third-party Cookies: those sent to the user&rsquo;s device from a unit or domain not managed by the editor but by other entity that uses the data obtained through the cookies. </p>
    <p>3.- Session Cookies: those designed to gather and store data while the user accesses to a web. </p>
    <p>4.- Persistent Cookies: those in which the data stored remains on the device and can be accessed to during certain amount of time defined by the responsible of the cookie. That period of time may be minutes or maybe even years. </p>
    <p>5.- Multimedia Content Player cookies: those that allow users to browse a web and use the various options or services found on it, for example, control data traffic and communication, session identification, access certain restricted content, remember elements included in an order, store contents in order to broadcast videos or sounds or share contents by using the social media. </p>
    <p>6.- User-interface Customization Cookies: those that allow users access to the service with certain general default characteristics according to a specific criteria within the user&rsquo;s device, as for example, language, kind of browser used in order to access certain services, etc. </p>
    <p>7.- Analytic Cookies: those used by us or by third parties which allow to quantify the number of users and therefore statistically measure and analyze how users use services offered on the Web. We analyze navigation on our web to improve the products or services that we provide.</p>
    <p>8.- Advertising Cookies: those that allow management, as accurate as possible, of the advertising space that, when appropriate, the editor has included on a Web, app or platform from which the service is provided according to certain criteria like the edited content or the frequency in which ads are shown. </p>
    <p>9.- Behavioural Advertising Cookies: those that allow management, as accurate as possible, of the advertising space that, when appropriate, the editor has included on a Web, app or platform from which the service is provided. These cookies store information about users behaviour obtained through continual observation of their browsing habits, which allows to develop a specific profile in order to show specific advertising according to it. </p>
<p align="justify"> <strong>- TYPES OF COOKIES USED BY THIS WEB</strong></p>
<p align="justify">This web uses session and third-party cookies which allow us to store and access to information related to language, kind of browser used and other general characteristics preferred by the user, as well as monitor and analyze users activity in order to provide more personalized and efficient services. INVERSIONES HOSTELERAS DE GALICIA, S.L., does not use advertising cookies nor behavioural advertising cookies.</p>
<p align="justify">By using these cookies we are able to offer advantages in the provision of services since it facilitates users browsing and access to the various services that our web offers; thanks to them users can avoid having to configure general default characteristics every time they visit the web; they contribute to the improvement of the functioning and of the services provided through the web, after the appropriate information analysis obtained via cookies.</p>


<div class="col-xs-12"><h2>Cookie - ocahotels.com</h2></div>
<style type="text/css">
    .padIt div{
        padding: 4px;
    }
</style>
<div class="padIt">
<div class="col-xs-12 "><h3>Name</h3><p>_ga</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Type</h5><p>Third party (Google Analytics)</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Purpose</h5><p>It is used to distinguish users.</p></div>
<div class="col-xs-12 col-sm-6 col-md-2"><h5>Duration</h5><p>2 years</p></div>
<div class="col-xs-12 col-sm-6 col-md-4" style="word-wrap: break-word;"><h5>More information</h5><p><a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es-419">https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es-419</a></p></div>

<div class="col-xs-12"><hr></div>


<div class="col-xs-12 "><h3>Name</h3><p>_gat</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Type</h5><p>Third party (Google Analytics)</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Purpose</h5><p>The cookie is created when the javascript library is loaded and there is no previous version of the _gat cookie.</p></div>
<div class="col-xs-12 col-sm-6 col-md-2"><h5>Duration</h5><p>End of session</p></div>
<div class="col-xs-12 col-sm-6 col-md-4" style="word-wrap: break-word;"><h5>More information</h5><p><a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es-419">https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es-419</a></p></div>

<div class="col-xs-12"><hr></div>


<div class="col-xs-12 "><h3>Name</h3><p>_gid</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Type</h5><p>Third party (Google Analytics)</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Purpose</h5><p>It is an analytical cookie, related to Google Analytics that is used to distinguish users.</p></div>
<div class="col-xs-12 col-sm-6 col-md-2"><h5>Duration</h5><p>1 día</p></div>
<div class="col-xs-12 col-sm-6 col-md-4" style="word-wrap: break-word;"><h5>More information</h5><p><a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es-419">https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es-419</a></p></div>
<div class="col-xs-12"><hr></div>

<div class="col-xs-12 "><h3>Name</h3><p>6c046e19abae502b6c47ff83a8eb4d8727f7dd4e</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Type</h5><p>own</p></div>

<div class="col-xs-12 col-sm-6 col-md-2"><h5>Duration</h5><p>2 years</p></div>


<div class="col-xs-12"><hr></div>


<div class="col-xs-12 "><h3>Name</h3><p>a98e53615d37a31cc52f76d8ef02a22318bae5df</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Type</h5><p>own</p></div>

<div class="col-xs-12 col-sm-6 col-md-2"><h5>Duration</h5><p>2 years</p></div>


<div class="col-xs-12"><hr></div>


<div class="col-xs-12 "><h3>Name</h3><p>dd898f14bdc9dab95346cf7057db6ffdb10ba1c8</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Type</h5><p>own</p></div>

<div class="col-xs-12 col-sm-6 col-md-2"><h5>Duration</h5><p>2 years</p></div>


<div class="col-xs-12"><hr></div>

<div class="col-xs-12 "><h3>Name</h3><p>240plan y 240planBAK</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Type</h5><p>Third party (Google Analytics)</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Purpose</h5><p>Technical Cookie.</p></div>
<div class="col-xs-12 col-sm-6 col-md-2"><h5>Duration</h5><p>End of session</p></div>

<div class="col-xs-12"><hr></div>

<div class="col-xs-12 "><h3>Name</h3><p>Cookies_consent</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Type</h5><p>Own</p></div>
<div class="col-xs-12 col-sm-6 col-md-3"><h5>Purpose</h5><p>Indicates that the user has accepted the cookies policy
 </p></div>
<div class="col-xs-12 col-sm-6 col-md-2"><h5>Duration</h5><p>1 month</p></div>

<div class="col-xs-12"><hr></div>



</div>



<div class="row"></div>

<p align="justify">ADDITIONAL NOTE: Embedded content is shown on some webs of this site through which third-party cookies may be being installed. Although webs are revised from time to time it may happen that the cookies list is not updated. If you wish to ask any question regarding cookies that may be installed through this web, please, do not hesitate to contact us. </p>



<p>&nbsp;DISABLING COOKIES:</p>
<p>Users can, at any time, access their browsing configuration accepting or rejecting all cookies or selecting those whose installation is wanted or not. In order to do so, users must follow the following procedures, which depend on the browser they use:</p>
    <p>Since each browser uses a different way of disabling cookies, the &ldquo;help&rdquo; function will explain you how to do it:</p>
    <p><br/>
    </p>
    <p>•Internet Explorer: <a href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies"><u>https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies</u></a></p>
    <p>• FireFox: <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences#w_how-do-i-change-cookie-settings"><u>https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences#w_how-do-i-change-cookie-settings</u></a></p>
    <p>•Chrome: <a href="https://support.google.com/chrome/answer/95647?hl=%22en"><u>https://support.google.com/chrome/answer/95647?hl=%22en</u></a></p>
    <p>•Safari: <a href="https://www.apple.com/legal/privacy/en-ww/cookies/"><u>https://www.apple.com/legal/privacy/en-ww/cookies/</u></a></p>
    <p><br/>
    </p>
    <p>All browsers allow you to change the Cookie configuration. These settings are usually found on the &ldquo;Option&rdquo; or &ldquo;Preference&rdquo; sections of your browser menu. </p>
    <p>Below you will find further information about the steps needed in order to access the  cookies&rsquo; configuration menu and, in each option, information referring to the private browsing of each of the main browsers:</p>
    <p><br/>
    </p>
    <p>Internet Explorer: <strong>Tools</strong> -&gt; <strong>Internet options</strong> -&gt; <strong>Privacy</strong> -&gt;<strong>Settings</strong>. For further, information you may consult <a href="https://support.microsoft.com/en-gb/products/microsoft-account"><u>Microsoft support</u></a> or browser &ldquo;Help&rdquo;.</p>
    <p><br/>
    </p>
    <p>Firefox: <strong>Tools</strong> -&gt; <strong>Options</strong> -&gt; <strong>Privacy &amp; Security</strong> -&gt; <strong>History</strong> -&gt; <strong>Use custom settings for history</strong>. For further information, you may consult <a href="https://support.mozilla.org/en-US/"><u>Mozilla support</u></a> or browser &ldquo;Help&rdquo;.</p>
    <p><br/>
    </p>
    <p>Chrome: <strong>Settings</strong>-&gt; <strong>Show advanced settings</strong> -&gt; in &ldquo;Privacy&rdquo; click <strong>Content settings</strong> -&gt; under &ldquo;Cookies&rdquo; click <strong>All cookies and site data</strong>. For further information, you may consult <a href="https://support.google.com/"><u>Chrome support</u></a> or browser &ldquo;Help&rdquo;.</p>
    <p><br/>
    </p>
    <p>Safari: <strong>Preferences</strong>-&gt; <strong>Privacy</strong>. For further information, you may consult <a href="https://support.apple.com/"><u>Apple support</u></a> or browser &ldquo;Help&rdquo;.</p>
    <p><br/>
    </p>
    <p>Should you have any further questions, please contact us by sending an e-mail to <a href="mailto:lopd@ocahotels.es"><u>lopd@ocahotels.es</u></a>. </p>
<p align="justify"><br/>
</p>
<p align="justify"><br/>
</p>
                
            </div>
        </div>
    </div>
    
</section>