<header class="intro-header">
    
    <div id="carousel-home" class="carousel slide " data-ride="carousel" data-interval="4000">

        <div class="carousel-inner" role="listbox">
            
            
                <div class="item active">
                   <div class="row ">
                       <div class="col-md-12 fill-40 fill-before-shadow" style="background-image: url('http://ocahotels.com/images/hoteles-con-golf/hoteles-con-golf-home.jpg')"></div>
                   </div>
               </div>
         
            
            <div class="carousel-caption">
                <h2 class="text-uppercase txt-220"><?php echo $titulo?></h2>
                <h3 style="font-weight: 300">Disfrute del placer del golf en los hoteles Oca</h3>
            </div>
            
        </div>
        
      

    </div>
    
</header>
    
    <?php include(getTmpl("tmpl_buscador_horizontal","main")) ?>
<section class="pd-t-50 pd-b-50 bck-color-gris">
    <div class="container content-interior">
        <div class="row">
           <div class="ol-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2 text-center">
              
               <h2 class="color-accion" style="line-height: inherit">Oca Augas Santas y Palacio de la Llorea, ponen al servicio de los aficionados al golf una amplia oferta deportiva gracias a su acceso a dos campos de golf únicos</h2>
               
                 
        </div>
            
           
            <div class="col-xs-12 col-xs-push-0 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2"> 

                
                <p>Los 18 hoyos de Augas Santas entre los que se dividen los más de 5.000 metros de campo, gozan de un relieve prácticamente llano y unos greens francos y bien protegidos. </p>
                <p>
                  Un campo de golf único que disfrutará al máximo gracias a las instalaciones y los servicios que ofrece el Club de Golf Augas Santas, como su cancha de prácticas, putting-green, zona de aproach con bunker de prácticas, tienda de golf, escuela deportiva, alquiler de equipo, e incluso clases privadas a manos de profesionales.
                </p>
                <p>Palacio de la Llorea cuenta con un acuerdo de colaboración con Campo de Golf de La Llorea, lo que permite a nuestros clientes tener acceso completo a los 18 hoyos de este campo de golf ubicado en una rasa costera a 100 metros sobre el nivel del mar, ofreciendo unas vistas inmejorables mientras disfruta de un fantástico día de golf.</p>
            <br>
                    <a href="https://podio.com/webforms/19688648/1334904?fields[en-que-esta-interesad]=2" target="_blank" class="pdflink"><h4>SOLICITAR INFORMACIÓN</h4></a>
              </div>
          
           
    </div>
    </div>
</section>


<div class="row boxes-destinos">
        
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/augas-santas/augas-santas-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Augas Santas</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Pantón, Lugo</p>

                        <a href="/hoteles/espana/lugo/panton/oca-augas-santas/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              
                <div class="text-center back-image5 hotel-normal" style="margin-bottom:20px !important; min-height: 400px;background-image: url('/images/hoteles/palacio-de-la-llorea/palacio-de-la-llorea-home.jpg')">
                  
                    <div class="ps-rel wd-100" style="top:0;background:rgba(0,0,0,0.2);min-height: 400px;height: 400px;">

                        <h3>Palacio de la Llorea</h3>

                        <div class="txt-200 mg-b-10 " style="color:#FFF">
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                        <i class="fa icon-estrella"></i> 
                                                    </div>
                        <p class="color-blanco font-light txt-130">Gijón, Asturias</p>

                        <a href="/hoteles/espana/asturias/gijon/oca-palacio-llorea/" class="btn btn-primary-box mg-t-50" style="top:0;">DESCÚBRELO</a>
                      
                    </div>
 
                </div>
                
            </div>
                        
        </div>
<?php GestionTemplates::getTmplInclude("tmpl_newsletter","main") ?>



